// 指南 · 西方科学家 · 48 题
// 12 维 × 4 题；侧重思辨 / 革新 / 学识 / 风险
// 注：每题设 1 个 primary delta = 0 的中性锚点选项，代表不偏不倚，属有意设计

import type { Item } from './item.types';

export const ITEMS_WEST_SCIENTIST: readonly Item[] = [
  // ── T1 思辨 ──
  {
    id: 'ws-r01',
    format: 'ranking',
    prompt: '科学之法',
    promptGloss: '「观察、假设、实验、证伪」── 科学之法，何者最贵？',
    options: [
      { text: '观察为本', gloss: '以目为始', primary: { traitId: 1, delta: -0.6 } },
      { text: '假设为径', gloss: '以推为先', primary: { traitId: 1, delta: 0.6 } },
      { text: '实验为证', gloss: '以验为据', primary: { traitId: 1, delta: 1 } },
      { text: '证伪为要', gloss: '以否为进', primary: { traitId: 1, delta: 1.4 } },
      { text: '四者并重', gloss: '相辅相成', primary: { traitId: 1, delta: 0 } },
      { text: '循序而行', gloss: '次第用之', primary: { traitId: 1, delta: 0.4 } },
    ],
  },
  {
    id: 'ws-a01',
    format: 'aesthetic',
    prompt: '日心与地心',
    promptGloss: '日心之灿与地心之稳，宇宙图景，何者更美？',
    options: [
      { text: '前者', gloss: '前者更合心意', primary: { traitId: 1, delta: 1.2 } },
      { text: '偏前者', gloss: '略偏前者之境', primary: { traitId: 1, delta: 0.6 }, secondary: [{ traitId: 6, delta: 0.2 }] },
      { text: '兼爱之', gloss: '两种意境皆有可取', primary: { traitId: 1, delta: 0 }, secondary: [{ traitId: 6, delta: 0.3 }] },
      { text: '偏后者', gloss: '略偏后者之境', primary: { traitId: 1, delta: -0.6 }, secondary: [{ traitId: 6, delta: -0.2 }] },
      { text: '后者', gloss: '后者更入君心', primary: { traitId: 1, delta: -1.2 } },
      { text: '皆不取', gloss: '超乎二者之外', primary: { traitId: 1, delta: -1.4 }, secondary: [{ traitId: 1, delta: 0.2 }] },
    ],
  },
  {
    id: 'ws-003',
    format: 'imagery',
    prompt: '可见与可知',
    promptGloss: '汝欲见何物？',
    options: [
      { text: '眼前之影', gloss: '以见为真', primary: { traitId: 1, delta: -1.2 } },
      { text: '经验之集', gloss: '以验为真', primary: { traitId: 1, delta: -0.4 } },
      { text: '模型之图', gloss: '以图为真', primary: { traitId: 1, delta: 0.6 } },
      { text: '数学之式', gloss: '以式为真', primary: { traitId: 1, delta: 1.0 } },
      { text: '逻辑之链', gloss: '以推为真', primary: { traitId: 1, delta: 1.2 } },
      { text: '先验之构', gloss: '以理为先', primary: { traitId: 1, delta: 1.5 } },
    ],
  },
  {
    id: 'ws-004',
    format: 'situational',
    prompt: '未证之理',
    promptGloss: '一理尚未证，汝敢言其有乎？',
    options: [
      { text: '不敢言', gloss: '以不证不言', primary: { traitId: 1, delta: -1.5 } },
      { text: '存疑可也', gloss: '暂不立论', primary: { traitId: 1, delta: -0.6 } },
      { text: '以理推之', gloss: '推而不证', primary: { traitId: 1, delta: 0.4 } },
      { text: '假设以立', gloss: '立而待证', primary: { traitId: 1, delta: 0.8 } },
      { text: '敢言之', gloss: '以理为足', primary: { traitId: 1, delta: 1.2 } },
      { text: '立而证之', gloss: '以行为证', primary: { traitId: 1, delta: 1.5 } },
    ],
  },

  // ── T2 情感 ──
  {
    id: 'ws-r02',
    format: 'ranking',
    prompt: '探索之情',
    promptGloss: '「冷静、好奇、热忱、痴狂」── 探索之心，何者最真？',
    options: [
      { text: '冷静观照', gloss: '以冷为度', primary: { traitId: 2, delta: -0.8 } },
      { text: '好奇为力', gloss: '以奇为驱', primary: { traitId: 2, delta: 0.6 } },
      { text: '热忱为火', gloss: '以热为度', primary: { traitId: 2, delta: 1 } },
      { text: '痴狂为极', gloss: '以狂为归', primary: { traitId: 2, delta: 1.4 } },
      { text: '平淡以对', gloss: '不动于心', primary: { traitId: 2, delta: 0 } },
      { text: '因事而发', gloss: '随遇而安', primary: { traitId: 2, delta: -0.4 } },
    ],
  },
  {
    id: 'ws-a02',
    format: 'aesthetic',
    prompt: '寒泉与焰火',
    promptGloss: '寒泉之冷静与焰火之热烈，探索之心，何态更美？',
    options: [
      { text: '前者', gloss: '前者更合心意', primary: { traitId: 2, delta: 1.2 } },
      { text: '偏前者', gloss: '略偏前者之境', primary: { traitId: 2, delta: 0.6 }, secondary: [{ traitId: 6, delta: 0.2 }] },
      { text: '兼爱之', gloss: '两种意境皆有可取', primary: { traitId: 2, delta: 0 }, secondary: [{ traitId: 6, delta: 0.3 }] },
      { text: '偏后者', gloss: '略偏后者之境', primary: { traitId: 2, delta: -0.6 }, secondary: [{ traitId: 6, delta: -0.2 }] },
      { text: '后者', gloss: '后者更入君心', primary: { traitId: 2, delta: -1.2 } },
      { text: '皆不取', gloss: '超乎二者之外', primary: { traitId: 2, delta: -1.4 }, secondary: [{ traitId: 1, delta: 0.2 }] },
    ],
  },
  {
    id: 'ws-007',
    format: 'imagery',
    prompt: '冷月之思',
    promptGloss: '汝于独处，心境为何？',
    options: [
      { text: '寒冰', gloss: '以冷为度', primary: { traitId: 2, delta: -1.2 } },
      { text: '古井', gloss: '以静为度', primary: { traitId: 2, delta: -0.6 } },
      { text: '明镜', gloss: '以明为度', primary: { traitId: 2, delta: 0.0 } },
      { text: '灯焰', gloss: '以明为度', primary: { traitId: 2, delta: 0.6 } },
      { text: '烈火', gloss: '以炽为度', primary: { traitId: 2, delta: 1.2 } },
      { text: '太阳', gloss: '以极炽为度', primary: { traitId: 2, delta: 1.5 } },
    ],
  },
  {
    id: 'ws-008',
    format: 'situational',
    prompt: '真理之美',
    promptGloss: '当一理之美动汝心，汝何以应？',
    options: [
      { text: '不动于色', gloss: '以理节美', primary: { traitId: 2, delta: -1.2 } },
      { text: '淡然记之', gloss: '不以为意', primary: { traitId: 2, delta: -0.4 } },
      { text: '欣然会之', gloss: '以会为度', primary: { traitId: 2, delta: 0.4 } },
      { text: '动容以叹', gloss: '以叹为度', primary: { traitId: 2, delta: 0.8 } },
      { text: '心为所摄', gloss: '以摄为度', primary: { traitId: 2, delta: 1.2 } },
      { text: '忘言忘身', gloss: '以忘为度', primary: { traitId: 2, delta: 1.5 } },
    ],
  },

  // ── T3 行动 ──
  {
    id: 'ws-r03',
    format: 'ranking',
    prompt: '研究之序',
    promptGloss: '「构想、计算、实验、应用」── 研究之序，何者最重？',
    options: [
      { text: '构想为重', gloss: '以思为先', primary: { traitId: 3, delta: -0.6 } },
      { text: '计算为上', gloss: '以数为基', primary: { traitId: 3, delta: 0.2 } },
      { text: '实验为径', gloss: '以验为度', primary: { traitId: 3, delta: 0.8 } },
      { text: '应用为归', gloss: '以致用为终', primary: { traitId: 3, delta: 1.2 } },
      { text: '循环往复', gloss: '迭代为上', primary: { traitId: 3, delta: 0 } },
      { text: '不拘一格', gloss: '因需而定', primary: { traitId: 3, delta: 0.4 } },
    ],
  },
  {
    id: 'ws-010',
    format: 'situational',
    prompt: '千试一得',
    promptGloss: '一器之成必经千次失败，汝当如何？',
    options: [
      { text: '不试', gloss: '不为之', primary: { traitId: 3, delta: -1.5 } },
      { text: '试而不成止', gloss: '不耐久试', primary: { traitId: 3, delta: -0.8 } },
      { text: '百试', gloss: '以百为度', primary: { traitId: 3, delta: 0.0 } },
      { text: '千试', gloss: '以千为度', primary: { traitId: 3, delta: 0.8 } },
      { text: '万试', gloss: '以万为度', primary: { traitId: 3, delta: 1.2 } },
      { text: '试至天荒', gloss: '不止不息', primary: { traitId: 3, delta: 1.5 } },
    ],
  },
  {
    id: 'ws-011',
    format: 'imagery',
    prompt: '方程与器',
    promptGloss: '理论与实验，汝更重哪一端？',
    options: [
      { text: '纸上', gloss: '止于笔端', primary: { traitId: 3, delta: -1.2 } },
      { text: '图中', gloss: '以图为归', primary: { traitId: 3, delta: -0.4 } },
      { text: '实验', gloss: '以验为归', primary: { traitId: 3, delta: 0.6 } },
      { text: '机中', gloss: '以器为归', primary: { traitId: 3, delta: 1.0 } },
      { text: '万用', gloss: '以用为归', primary: { traitId: 3, delta: 1.2 } },
      { text: '造物', gloss: '以创为归', primary: { traitId: 3, delta: 1.5 } },
    ],
  },
  {
    id: 'ws-012',
    format: 'situational',
    prompt: '屡败屡试',
    promptGloss: '实验屡败，汝何以处？',
    options: [
      { text: '沮丧而止', gloss: '以止为度', primary: { traitId: 3, delta: -1.5 } },
      { text: '暂歇再试', gloss: '以暂为度', primary: { traitId: 3, delta: -0.4 } },
      { text: '审思其因', gloss: '以思促行', primary: { traitId: 3, delta: 0.4 } },
      { text: '改法再试', gloss: '以变为度', primary: { traitId: 3, delta: 0.8 } },
      { text: '愈挫愈奋', gloss: '以挫为度', primary: { traitId: 3, delta: 1.2 } },
      { text: '以身为殉', gloss: '以死为度', primary: { traitId: 3, delta: 1.5 } },
    ],
  },

  // ── T4 革新 ──
  {
    id: 'ws-r04',
    format: 'ranking',
    prompt: '范式之变',
    promptGloss: '「继承、修正、革命、超越」── 科学跃进，何者最关键？',
    options: [
      { text: '继承为基', gloss: '以承为本', primary: { traitId: 4, delta: -1 } },
      { text: '修正渐改', gloss: '以改为进', primary: { traitId: 4, delta: -0.2 } },
      { text: '彻底革命', gloss: '以破为立', primary: { traitId: 4, delta: 1 } },
      { text: '超越前人', gloss: '以超为度', primary: { traitId: 4, delta: 1.4 } },
      { text: '择善而从', gloss: '取长补短', primary: { traitId: 4, delta: 0 } },
      { text: '相融并进', gloss: '新旧相生', primary: { traitId: 4, delta: 0.4 } },
    ],
  },
  {
    id: 'ws-a04',
    format: 'aesthetic',
    prompt: '旧图与新典',
    promptGloss: '旧图斑驳与新典初成，知识更替，何者更动君心？',
    options: [
      { text: '前者', gloss: '前者更合心意', primary: { traitId: 4, delta: 1.2 } },
      { text: '偏前者', gloss: '略偏前者之境', primary: { traitId: 4, delta: 0.6 }, secondary: [{ traitId: 6, delta: 0.2 }] },
      { text: '兼爱之', gloss: '两种意境皆有可取', primary: { traitId: 4, delta: 0 }, secondary: [{ traitId: 6, delta: 0.3 }] },
      { text: '偏后者', gloss: '略偏后者之境', primary: { traitId: 4, delta: -0.6 }, secondary: [{ traitId: 6, delta: -0.2 }] },
      { text: '后者', gloss: '后者更入君心', primary: { traitId: 4, delta: -1.2 } },
      { text: '皆不取', gloss: '超乎二者之外', primary: { traitId: 4, delta: -1.4 }, secondary: [{ traitId: 1, delta: 0.2 }] },
    ],
  },
  {
    id: 'ws-015',
    format: 'imagery',
    prompt: '旧瓶新酒',
    promptGloss: '新理已得，汝欲何载？',
    options: [
      { text: '旧瓶', gloss: '以旧载新', primary: { traitId: 4, delta: -0.8 } },
      { text: '半新半旧', gloss: '以中为度', primary: { traitId: 4, delta: 0.0 } },
      { text: '新瓶旧酒', gloss: '以新载旧', primary: { traitId: 4, delta: 0.4 } },
      { text: '新瓶新酒', gloss: '以新载新', primary: { traitId: 4, delta: 0.8 } },
      { text: '破瓶倾酒', gloss: '以破为度', primary: { traitId: 4, delta: 1.2 } },
      { text: '无瓶无酒', gloss: '以不立为度', primary: { traitId: 4, delta: 1.5 } },
    ],
  },
  {
    id: 'ws-016',
    format: 'situational',
    prompt: '新代旧',
    promptGloss: '新理已立，旧制尚存，汝何从？',
    options: [
      { text: '守旧', gloss: '以旧为度', primary: { traitId: 4, delta: -1.2 } },
      { text: '新旧并行', gloss: '以并行为度', primary: { traitId: 4, delta: -0.4 } },
      { text: '以旧证新', gloss: '以旧为证', primary: { traitId: 4, delta: 0.4 } },
      { text: '以新辅旧', gloss: '以新为辅', primary: { traitId: 4, delta: 0.6 } },
      { text: '以新代旧', gloss: '以新物代旧物', primary: { traitId: 4, delta: 1.0 } },
      { text: '化旧为新', gloss: '以化为度', primary: { traitId: 4, delta: 1.5 } },
    ],
  },

  // ── T5 群我 ──
  {
    id: 'ws-r05',
    format: 'ranking',
    prompt: '知识之域',
    promptGloss: '「一己、同道、学界、人类」── 知识之域，何者最重？',
    options: [
      { text: '一己之知', gloss: '以私为度', primary: { traitId: 5, delta: -1.2 } },
      { text: '同道与共', gloss: '以友为度', primary: { traitId: 5, delta: -0.2 } },
      { text: '学界为先', gloss: '以群体为度', primary: { traitId: 5, delta: 0.6 } },
      { text: '惠及人类', gloss: '以天下为度', primary: { traitId: 5, delta: 1.4 } },
      { text: '顺其自然', gloss: '随缘而传', primary: { traitId: 5, delta: 0 } },
      { text: '传之久远', gloss: '以永为度', primary: { traitId: 5, delta: 1 } },
    ],
  },
  {
    id: 'ws-a05',
    format: 'aesthetic',
    prompt: '萤火与星河',
    promptGloss: '萤火之微光与星河之浩瀚，知识所照，何境更美？',
    options: [
      { text: '前者', gloss: '前者更合心意', primary: { traitId: 5, delta: 1.2 } },
      { text: '偏前者', gloss: '略偏前者之境', primary: { traitId: 5, delta: 0.6 }, secondary: [{ traitId: 6, delta: 0.2 }] },
      { text: '兼爱之', gloss: '两种意境皆有可取', primary: { traitId: 5, delta: 0 }, secondary: [{ traitId: 6, delta: 0.3 }] },
      { text: '偏后者', gloss: '略偏后者之境', primary: { traitId: 5, delta: -0.6 }, secondary: [{ traitId: 6, delta: -0.2 }] },
      { text: '后者', gloss: '后者更入君心', primary: { traitId: 5, delta: -1.2 } },
      { text: '皆不取', gloss: '超乎二者之外', primary: { traitId: 5, delta: -1.4 }, secondary: [{ traitId: 1, delta: 0.2 }] },
    ],
  },
  {
    id: 'ws-019',
    format: 'imagery',
    prompt: '一灯万灯',
    promptGloss: '独研与传承，汝如何选择？',
    options: [
      { text: '一隅', gloss: '以一为度', primary: { traitId: 5, delta: -1.0 } },
      { text: '一室', gloss: '以室为度', primary: { traitId: 5, delta: -0.4 } },
      { text: '一城', gloss: '以城为度', primary: { traitId: 5, delta: 0.2 } },
      { text: '一国', gloss: '以国为度', primary: { traitId: 5, delta: 0.6 } },
      { text: '一洲', gloss: '以洲为度', primary: { traitId: 5, delta: 1.0 } },
      { text: '万邦共照', gloss: '以万为度', primary: { traitId: 5, delta: 1.5 } },
    ],
  },
  {
    id: 'ws-020',
    format: 'situational',
    prompt: '独研与共研',
    promptGloss: '为学当独，抑或共？',
    options: [
      { text: '独研', gloss: '以独为度', primary: { traitId: 5, delta: -0.6 } },
      { text: '半独半共', gloss: '以中为度', primary: { traitId: 5, delta: 0.0 } },
      { text: '合众共研', gloss: '以合为度', primary: { traitId: 5, delta: 0.6 } },
      { text: '立学会共研', gloss: '以会为度', primary: { traitId: 5, delta: 1.0 } },
      { text: '跨国共研', gloss: '以国为度', primary: { traitId: 5, delta: 1.2 } },
      { text: '天下共研', gloss: '以天下为度', primary: { traitId: 5, delta: 1.5 } },
    ],
  },

  // ── T6 审美 ──
  {
    id: 'ws-021',
    format: 'imagery',
    prompt: '方程之美',
    promptGloss: '汝观一理，何者动汝？',
    options: [
      { text: '用之美', gloss: '以用为美', primary: { traitId: 6, delta: -1.0 } },
      { text: '简之美', gloss: '以简为美', primary: { traitId: 6, delta: -0.4 } },
      { text: '整之美', gloss: '以整为美', primary: { traitId: 6, delta: 0.0 } },
      { text: '对之美', gloss: '以对为美', primary: { traitId: 6, delta: 0.4 } },
      { text: '和之美', gloss: '以和为美', primary: { traitId: 6, delta: 0.8 } },
      { text: '神之美', gloss: '以神为美', primary: { traitId: 6, delta: 1.5 } },
    ],
  },
  {
    id: 'ws-r06',
    format: 'ranking',
    prompt: '宇宙之美',
    promptGloss: '「对称、简洁、统一、神秘」── 宇宙之象，何者最美？',
    options: [
      { text: '对称之美', gloss: '以对为美', primary: { traitId: 6, delta: -0.6 } },
      { text: '简洁为上', gloss: '以简为美', primary: { traitId: 6, delta: 0 } },
      { text: '统一为归', gloss: '以统为美', primary: { traitId: 6, delta: 0.8 } },
      { text: '神秘为深', gloss: '以玄为美', primary: { traitId: 6, delta: 1.4 } },
      { text: '各美其美', gloss: '不拘一格', primary: { traitId: 6, delta: 0.4 } },
      { text: '无美无丑', gloss: '超越美丑', primary: { traitId: 6, delta: -0.4 } },
    ],
  },
  {
    id: 'ws-a06',
    format: 'aesthetic',
    prompt: '抛物线与星轨',
    promptGloss: '地上抛体之弧与天上行星之轨，宇宙之美，何者更动汝？',
    options: [
      { text: '前者', gloss: '前者更合心意', primary: { traitId: 6, delta: 1.2 } },
      { text: '偏前者', gloss: '略偏前者之境', primary: { traitId: 6, delta: 0.6 }, secondary: [{ traitId: 6, delta: 0.2 }] },
      { text: '兼爱之', gloss: '两种意境皆有可取', primary: { traitId: 6, delta: 0 }, secondary: [{ traitId: 6, delta: 0.3 }] },
      { text: '偏后者', gloss: '略偏后者之境', primary: { traitId: 6, delta: -0.6 }, secondary: [{ traitId: 6, delta: -0.2 }] },
      { text: '后者', gloss: '后者更入君心', primary: { traitId: 6, delta: -1.2 } },
      { text: '皆不取', gloss: '超乎二者之外', primary: { traitId: 6, delta: -1.4 }, secondary: [{ traitId: 1, delta: 0.2 }] },
    ],
  },
  {
    id: 'ws-024',
    format: 'imagery',
    prompt: '宇宙之象',
    promptGloss: '汝于宇宙之美，何者动汝？',
    options: [
      { text: '秩序', gloss: '以序为美', primary: { traitId: 6, delta: -0.4 } },
      { text: '对偶', gloss: '以对为美', primary: { traitId: 6, delta: 0.0 } },
      { text: '繁星', gloss: '以多为美', primary: { traitId: 6, delta: 0.4 } },
      { text: '幽微', gloss: '以微为美', primary: { traitId: 6, delta: 0.8 } },
      { text: '宏阔', gloss: '以大为美', primary: { traitId: 6, delta: 1.2 } },
      { text: '至美', gloss: '以至美为度', primary: { traitId: 6, delta: 1.5 } },
    ],
  },

  // ── T7 意志 ──
  {
    id: 'ws-r07',
    format: 'ranking',
    prompt: '求真之志',
    promptGloss: '「忍耐、执着、牺牲、狂热」── 求真路上，何德最贵？',
    options: [
      { text: '忍耐为先', gloss: '以忍为度', primary: { traitId: 7, delta: 0.4 } },
      { text: '执着为力', gloss: '以执为进', primary: { traitId: 7, delta: 0.8 } },
      { text: '勇于牺牲', gloss: '以舍为取', primary: { traitId: 7, delta: 1 } },
      { text: '狂热至极', gloss: '以狂为归', primary: { traitId: 7, delta: 1.4 } },
      { text: '从容不迫', gloss: '以和为度', primary: { traitId: 7, delta: -0.6 } },
      { text: '知难而止', gloss: '以止为智', primary: { traitId: 7, delta: -0.4 } },
    ],
  },
  {
    id: 'ws-026',
    format: 'situational',
    prompt: '众讥汝痴',
    promptGloss: '众人讥汝痴狂，汝当如何？',
    options: [
      { text: '改弦易辙', gloss: '以从众止', primary: { traitId: 7, delta: -1.5 } },
      { text: '暂避其锋', gloss: '以避为度', primary: { traitId: 7, delta: -0.6 } },
      { text: '徐徐以辩', gloss: '以辩为度', primary: { traitId: 7, delta: 0.0 } },
      { text: '自持以行', gloss: '以行为度', primary: { traitId: 7, delta: 0.8 } },
      { text: '以身为殉', gloss: '以死为度', primary: { traitId: 7, delta: 1.5 } },
      { text: '不辩不答', gloss: '以不答为度', primary: { traitId: 7, delta: 0.6 } },
    ],
  },
  {
    id: 'ws-027',
    format: 'imagery',
    prompt: '金刚与卵石',
    promptGloss: '汝欲为金刚石，抑或卵石？',
    options: [
      { text: '卵石', gloss: '以柔为度', primary: { traitId: 7, delta: -1.0 } },
      { text: '砂砾', gloss: '以散为度', primary: { traitId: 7, delta: -0.4 } },
      { text: '青石', gloss: '以刚为度', primary: { traitId: 7, delta: 0.4 } },
      { text: '金刚石', gloss: '以极刚为度', primary: { traitId: 7, delta: 1.0 } },
      { text: '砺石', gloss: '以磨为度', primary: { traitId: 7, delta: 0.8 } },
      { text: '水晶', gloss: '以明为度', primary: { traitId: 7, delta: 1.5 } },
    ],
  },
  {
    id: 'ws-028',
    format: 'situational',
    prompt: '理论之穷',
    promptGloss: '研究走入绝境，汝何以自处？',
    options: [
      { text: '改道', gloss: '以变为度', primary: { traitId: 7, delta: -0.8 } },
      { text: '独行', gloss: '以独为度', primary: { traitId: 7, delta: 0.4 } },
      { text: '传之于人', gloss: '以传为度', primary: { traitId: 7, delta: 1.0 } },
      { text: '著书立说', gloss: '以言为度', primary: { traitId: 7, delta: 1.2 } },
      { text: '死守', gloss: '以死为度', primary: { traitId: 7, delta: 1.5 } },
      { text: '退而传道', gloss: '以退为度', primary: { traitId: 7, delta: 0.6 } },
    ],
  },

  // ── T8 学识 ──
  {
    id: 'ws-r08',
    format: 'ranking',
    prompt: '认知之阶',
    promptGloss: '「感官、数据、定律、理论」── 认知之阶，何者最基？',
    options: [
      { text: '感官为窗', gloss: '以感为基', primary: { traitId: 8, delta: -0.8 } },
      { text: '数据为据', gloss: '以数为基', primary: { traitId: 8, delta: 0.4 } },
      { text: '定律为规', gloss: '以律为基', primary: { traitId: 8, delta: 0.8 } },
      { text: '理论为归', gloss: '以理为基', primary: { traitId: 8, delta: 1.2 } },
      { text: '兼收并蓄', gloss: '层层递进', primary: { traitId: 8, delta: 0 } },
      { text: '以用为度', gloss: '择宜而从', primary: { traitId: 8, delta: -0.4 } },
    ],
  },
  {
    id: 'ws-a08',
    format: 'aesthetic',
    prompt: '显微镜与望远镜',
    promptGloss: '显微镜下之微与望远镜前之宏，认知之具，何者更令人神往？',
    options: [
      { text: '前者', gloss: '前者更合心意', primary: { traitId: 8, delta: 1.2 } },
      { text: '偏前者', gloss: '略偏前者之境', primary: { traitId: 8, delta: 0.6 }, secondary: [{ traitId: 6, delta: 0.2 }] },
      { text: '兼爱之', gloss: '两种意境皆有可取', primary: { traitId: 8, delta: 0 }, secondary: [{ traitId: 6, delta: 0.3 }] },
      { text: '偏后者', gloss: '略偏后者之境', primary: { traitId: 8, delta: -0.6 }, secondary: [{ traitId: 6, delta: -0.2 }] },
      { text: '后者', gloss: '后者更入君心', primary: { traitId: 8, delta: -1.2 } },
      { text: '皆不取', gloss: '超乎二者之外', primary: { traitId: 8, delta: -1.4 }, secondary: [{ traitId: 1, delta: 0.2 }] },
    ],
  },
  {
    id: 'ws-031',
    format: 'imagery',
    prompt: '井与星海',
    promptGloss: '已知与未知，汝更愿居哪一端？',
    options: [
      { text: '井', gloss: '以井为度', primary: { traitId: 8, delta: -0.6 } },
      { text: '池', gloss: '以池为度', primary: { traitId: 8, delta: -0.2 } },
      { text: '湖', gloss: '以湖为度', primary: { traitId: 8, delta: 0.2 } },
      { text: '江', gloss: '以江为度', primary: { traitId: 8, delta: 0.6 } },
      { text: '海', gloss: '以海为度', primary: { traitId: 8, delta: 1.0 } },
      { text: '海纳百川', gloss: '以纳为度', primary: { traitId: 8, delta: 1.5 } },
    ],
  },
  {
    id: 'ws-032',
    format: 'situational',
    prompt: '通专之间',
    promptGloss: '通才与专才，汝愿为何？',
    options: [
      { text: '唯专', gloss: '以专为度', primary: { traitId: 8, delta: -0.4 } },
      { text: '半专半通', gloss: '以中为度', primary: { traitId: 8, delta: 0.0 } },
      { text: '唯通', gloss: '以通为度', primary: { traitId: 8, delta: 0.4 } },
      { text: '由专入通', gloss: '以专始通终', primary: { traitId: 8, delta: 0.8 } },
      { text: '由通入专', gloss: '以通始专终', primary: { traitId: 8, delta: 1.0 } },
      { text: '专而能通', gloss: '以兼为度', primary: { traitId: 8, delta: 1.5 } },
    ],
  },

  // ── T9 处世 ──
  {
    id: 'ws-r09',
    format: 'ranking',
    prompt: '学者之路',
    promptGloss: '「入世、独研、传道、归隐」── 学者之路，何者为上？',
    options: [
      { text: '投身世间', gloss: '以进为度', primary: { traitId: 9, delta: -1.2 } },
      { text: '独研于室', gloss: '以独为度', primary: { traitId: 9, delta: 0.4 } },
      { text: '传道授业', gloss: '以传为度', primary: { traitId: 9, delta: 1 } },
      { text: '归隐著书', gloss: '以隐为度', primary: { traitId: 9, delta: 1.4 } },
      { text: '行藏以时', gloss: '审时而动', primary: { traitId: 9, delta: 0 } },
      { text: '半入半隐', gloss: '两兼其中', primary: { traitId: 9, delta: -0.4 } },
    ],
  },
  {
    id: 'ws-a09',
    format: 'aesthetic',
    prompt: '孤岛与大陆',
    promptGloss: '孤岛之自足与大陆之广接，学者身处，何象更契？',
    options: [
      { text: '前者', gloss: '前者更合心意', primary: { traitId: 9, delta: 1.2 } },
      { text: '偏前者', gloss: '略偏前者之境', primary: { traitId: 9, delta: 0.6 }, secondary: [{ traitId: 6, delta: 0.2 }] },
      { text: '兼爱之', gloss: '两种意境皆有可取', primary: { traitId: 9, delta: 0 }, secondary: [{ traitId: 6, delta: 0.3 }] },
      { text: '偏后者', gloss: '略偏后者之境', primary: { traitId: 9, delta: -0.6 }, secondary: [{ traitId: 6, delta: -0.2 }] },
      { text: '后者', gloss: '后者更入君心', primary: { traitId: 9, delta: -1.2 } },
      { text: '皆不取', gloss: '超乎二者之外', primary: { traitId: 9, delta: -1.4 }, secondary: [{ traitId: 1, delta: 0.2 }] },
    ],
  },
  {
    id: 'ws-035',
    format: 'imagery',
    prompt: '舟与塔',
    promptGloss: '汝欲为舟，抑或塔？',
    options: [
      { text: '舟', gloss: '以行为度', primary: { traitId: 9, delta: -1.0 } },
      { text: '舴艋', gloss: '以小为度', primary: { traitId: 9, delta: -0.4 } },
      { text: '帆', gloss: '以动为度', primary: { traitId: 9, delta: 0.0 } },
      { text: '塔', gloss: '以立为度', primary: { traitId: 9, delta: 0.8 } },
      { text: '灯塔', gloss: '以守为度', primary: { traitId: 9, delta: 1.2 } },
      { text: '孤岛', gloss: '以独为度', primary: { traitId: 9, delta: 1.5 } },
    ],
  },
  {
    id: 'ws-036',
    format: 'situational',
    prompt: '发现之名',
    promptGloss: '发现传世与无名，汝何所求？',
    options: [
      { text: '不计', gloss: '以不名为度', primary: { traitId: 9, delta: -0.4 } },
      { text: '求当世名', gloss: '以当世为度', primary: { traitId: 9, delta: -0.2 } },
      { text: '求百世名', gloss: '以百世为度', primary: { traitId: 9, delta: 0.4 } },
      { text: '求万世名', gloss: '以万世为度', primary: { traitId: 9, delta: 1.0 } },
      { text: '求千古名', gloss: '以千古为度', primary: { traitId: 9, delta: 1.5 } },
      { text: '以名为累', gloss: '以忘为度', primary: { traitId: 9, delta: -0.6 } },
    ],
  },

  // ── T10 时间 ──
  {
    id: 'ws-r10',
    format: 'ranking',
    prompt: '传世之愿',
    promptGloss: '「当世用、利后学、铭史册、化万方」── 何者为愿？',
    options: [
      { text: '当世为用', gloss: '务求近效', primary: { traitId: 10, delta: -1 } },
      { text: '利在后学', gloss: '传于来者', primary: { traitId: 10, delta: 0.4 } },
      { text: '铭于史册', gloss: '刻石留名', primary: { traitId: 10, delta: 0.8 } },
      { text: '化育万方', gloss: '以化为功', primary: { traitId: 10, delta: 1.4 } },
      { text: '不求久远', gloss: '顺其自然', primary: { traitId: 10, delta: 0 } },
      { text: '以理为永', gloss: '理存即是', primary: { traitId: 10, delta: 1.2 } },
    ],
  },
  {
    id: 'ws-a10',
    format: 'aesthetic',
    prompt: '化石与新芽',
    promptGloss: '化石沉默之古与新芽初绽之嫩，时间熔铸，何者更美？',
    options: [
      { text: '前者', gloss: '前者更合心意', primary: { traitId: 10, delta: 1.2 } },
      { text: '偏前者', gloss: '略偏前者之境', primary: { traitId: 10, delta: 0.6 }, secondary: [{ traitId: 6, delta: 0.2 }] },
      { text: '兼爱之', gloss: '两种意境皆有可取', primary: { traitId: 10, delta: 0 }, secondary: [{ traitId: 6, delta: 0.3 }] },
      { text: '偏后者', gloss: '略偏后者之境', primary: { traitId: 10, delta: -0.6 }, secondary: [{ traitId: 6, delta: -0.2 }] },
      { text: '后者', gloss: '后者更入君心', primary: { traitId: 10, delta: -1.2 } },
      { text: '皆不取', gloss: '超乎二者之外', primary: { traitId: 10, delta: -1.4 }, secondary: [{ traitId: 1, delta: 0.2 }] },
    ],
  },
  {
    id: 'ws-039',
    format: 'imagery',
    prompt: '光阴真理',
    promptGloss: '一寸光阴与一尺真理，孰重？',
    options: [
      { text: '寸阴', gloss: '以寸阴为度', primary: { traitId: 10, delta: -0.6 } },
      { text: '兼取', gloss: '以兼为度', primary: { traitId: 10, delta: 0.0 } },
      { text: '尺璧', gloss: '以尺璧为度', primary: { traitId: 10, delta: 0.4 } },
      { text: '古之所贵', gloss: '以古为度', primary: { traitId: 10, delta: 0.6 } },
      { text: '寸阴难买', gloss: '以难为度', primary: { traitId: 10, delta: 1.0 } },
      { text: '与化同流', gloss: '以化为度', primary: { traitId: 10, delta: 1.5 } },
    ],
  },
  {
    id: 'ws-040',
    format: 'situational',
    prompt: '旧说新知',
    promptGloss: '旧说与新证，何从？',
    options: [
      { text: '今胜古', gloss: '以今为度', primary: { traitId: 10, delta: 0.4 } },
      { text: '古胜今', gloss: '以古为度', primary: { traitId: 10, delta: -0.4 } },
      { text: '各有所长', gloss: '以兼为度', primary: { traitId: 10, delta: 0.0 } },
      { text: '今为古继', gloss: '以继为度', primary: { traitId: 10, delta: 0.6 } },
      { text: '古为今基', gloss: '以基为度', primary: { traitId: 10, delta: 0.4 } },
      { text: '与化同新', gloss: '以化为度', primary: { traitId: 10, delta: 1.5 } },
    ],
  },

  // ── T11 风险 ──
  {
    id: 'ws-r11',
    format: 'ranking',
    prompt: '探索之限',
    promptGloss: '「不越雷池、试而无险、冒大险、不计生死」── 何者为界？',
    options: [
      { text: '不越雷池', gloss: '以安为度', primary: { traitId: 11, delta: -1.4 } },
      { text: '试而无险', gloss: '以慎为度', primary: { traitId: 11, delta: -0.4 } },
      { text: '甘冒大险', gloss: '以险为径', primary: { traitId: 11, delta: 0.8 } },
      { text: '不计生死', gloss: '以死为归', primary: { traitId: 11, delta: 1.4 } },
      { text: '审慎权衡', gloss: '以中为度', primary: { traitId: 11, delta: 0 } },
      { text: '见机而行', gloss: '伺机而动', primary: { traitId: 11, delta: 0.4 } },
    ],
  },
  {
    id: 'ws-a11',
    format: 'aesthetic',
    prompt: '静海与狂涛',
    promptGloss: '海面如镜之静与万丈波涛之险，探索之境，何者更唤人心？',
    options: [
      { text: '前者', gloss: '前者更合心意', primary: { traitId: 11, delta: 1.2 } },
      { text: '偏前者', gloss: '略偏前者之境', primary: { traitId: 11, delta: 0.6 }, secondary: [{ traitId: 6, delta: 0.2 }] },
      { text: '兼爱之', gloss: '两种意境皆有可取', primary: { traitId: 11, delta: 0 }, secondary: [{ traitId: 6, delta: 0.3 }] },
      { text: '偏后者', gloss: '略偏后者之境', primary: { traitId: 11, delta: -0.6 }, secondary: [{ traitId: 6, delta: -0.2 }] },
      { text: '后者', gloss: '后者更入君心', primary: { traitId: 11, delta: -1.2 } },
      { text: '皆不取', gloss: '超乎二者之外', primary: { traitId: 11, delta: -1.4 }, secondary: [{ traitId: 1, delta: 0.2 }] },
    ],
  },
  {
    id: 'ws-043',
    format: 'imagery',
    prompt: '孤理狂澜',
    promptGloss: '个人发现面对时代洪流，汝何以处？',
    options: [
      { text: '不渡', gloss: '以不渡为度', primary: { traitId: 11, delta: -1.5 } },
      { text: '近岸行', gloss: '以近为度', primary: { traitId: 11, delta: -0.6 } },
      { text: '半海', gloss: '以中为度', primary: { traitId: 11, delta: 0.0 } },
      { text: '远航', gloss: '以远为度', primary: { traitId: 11, delta: 0.6 } },
      { text: '穷海', gloss: '以穷为度', primary: { traitId: 11, delta: 1.0 } },
      { text: '与海同化', gloss: '以化为度', primary: { traitId: 11, delta: 1.5 } },
    ],
  },
  {
    id: 'ws-044',
    format: 'situational',
    prompt: '新理之争',
    promptGloss: '新理一立，旧派阻之，汝当如何？',
    options: [
      { text: '退让', gloss: '以让为度', primary: { traitId: 11, delta: -1.2 } },
      { text: '婉转', gloss: '以婉为度', primary: { traitId: 11, delta: -0.4 } },
      { text: '稳进', gloss: '以稳为度', primary: { traitId: 11, delta: 0.4 } },
      { text: '强推', gloss: '以强为度', primary: { traitId: 11, delta: 1.0 } },
      { text: '以死争之', gloss: '以死为度', primary: { traitId: 11, delta: 1.5 } },
      { text: '以行证之', gloss: '以行为度', primary: { traitId: 11, delta: 0.6 } },
    ],
  },

  // ── T12 表达 ──
  {
    id: 'ws-r12',
    format: 'ranking',
    prompt: '表达之式',
    promptGloss: '「口述、论文、方程、图卷」── 科学表达，何者最传神？',
    options: [
      { text: '口述相传', gloss: '以口为载', primary: { traitId: 12, delta: -0.8 } },
      { text: '论文为体', gloss: '以文为载', primary: { traitId: 12, delta: 0 } },
      { text: '方程立言', gloss: '以数为载', primary: { traitId: 12, delta: 0.8 } },
      { text: '图卷为器', gloss: '以象为载', primary: { traitId: 12, delta: 1.2 } },
      { text: '不言为言', gloss: '不载为载', primary: { traitId: 12, delta: -0.4 } },
      { text: '各择其宜', gloss: '因理而异', primary: { traitId: 12, delta: 0.4 } },
    ],
  },
  {
    id: 'ws-046',
    format: 'situational',
    prompt: '论文之辞',
    promptGloss: '科学论文中，文采与准确孰重？',
    options: [
      { text: '极简', gloss: '以简为度', primary: { traitId: 12, delta: -0.8 } },
      { text: '简', gloss: '以简为度', primary: { traitId: 12, delta: -0.4 } },
      { text: '适', gloss: '以适为度', primary: { traitId: 12, delta: 0.0 } },
      { text: '繁', gloss: '以繁为度', primary: { traitId: 12, delta: 0.4 } },
      { text: '极繁', gloss: '以繁为度', primary: { traitId: 12, delta: 1.0 } },
      { text: '图穷理现', gloss: '以图为度', primary: { traitId: 12, delta: 0.8 } },
    ],
  },
  {
    id: 'ws-047',
    format: 'imagery',
    prompt: '公式文字',
    promptGloss: '数学公式与文字解释，孰能载道？',
    options: [
      { text: '口耳', gloss: '以口为度', primary: { traitId: 12, delta: -1.2 } },
      { text: '册页', gloss: '以册为度', primary: { traitId: 12, delta: -0.4 } },
      { text: '书', gloss: '以书为度', primary: { traitId: 12, delta: 0.0 } },
      { text: '图', gloss: '以图为度', primary: { traitId: 12, delta: 0.6 } },
      { text: '式', gloss: '以式为度', primary: { traitId: 12, delta: 1.0 } },
      { text: '模', gloss: '以模为度', primary: { traitId: 12, delta: 1.5 } },
    ],
  },
  {
    id: 'ws-048',
    format: 'situational',
    prompt: '万语方程',
    promptGloss: '千言万语与一条方程，何者传世？',
    options: [
      { text: '千言', gloss: '以千为度', primary: { traitId: 12, delta: -0.4 } },
      { text: '半千', gloss: '以半为度', primary: { traitId: 12, delta: -0.6 } },
      { text: '百言', gloss: '以百为度', primary: { traitId: 12, delta: 0.0 } },
      { text: '十言', gloss: '以十为度', primary: { traitId: 12, delta: 0.4 } },
      { text: '一言', gloss: '以一为度', primary: { traitId: 12, delta: 1.0 } },
      { text: '无言', gloss: '以不立为度', primary: { traitId: 12, delta: 1.5 } },
    ],
  },
  {
    id: 'ws-049',
    format: 'situational',
    prompt: '同行质疑假说',
    promptGloss: '你发表了一项震惊学界的新假说，但同行们纷纷表示质疑，你如何应对？',
    options: [
      { text: '设计实验', gloss: '以实验数据证明之', primary: { traitId: 3, delta: 1.2 }, secondary: [{ traitId: 1, delta: 0.2 }] },
      { text: '据理答辩', gloss: '以理论推理说服之', primary: { traitId: 8, delta: 0.6 } },
      { text: '欢迎批判', gloss: '欢迎质疑以完善己论', primary: { traitId: 4, delta: 0.4 } },
      { text: '不为所动', gloss: '真理不因质疑而变', primary: { traitId: 7, delta: 0.8 } },
      { text: '心灰意冷', gloss: '无人理解，不如放弃', primary: { traitId: 2, delta: -1.2 } },
      { text: '寻求合作', gloss: '邀请质疑者共同验证', primary: { traitId: 11, delta: -0.4 } },
    ],
  },
  {
    id: 'ws-050',
    format: 'imagery',
    prompt: '实验室晨光',
    promptGloss: '清晨第一个走进实验室，晨曦透过窗户照在仪器上，你心中所感为何？',
    options: [
      { text: '新的开始', gloss: '新的一天，新的发现', primary: { traitId: 3, delta: 1.0 } },
      { text: '仪器之美', gloss: '精密的仪器如艺术品', primary: { traitId: 6, delta: 0.4 } },
      { text: '数据待查', gloss: '昨夜数据尚待分析', primary: { traitId: 7, delta: 0.8 } },
      { text: '前人足迹', gloss: '这些仪器凝结先贤智慧', primary: { traitId: 10, delta: 0.6 } },
      { text: '孤寂之路', gloss: '科研之路常伴孤独', primary: { traitId: 2, delta: -0.6 } },
      { text: '宁静致远', gloss: '此处静好，与世无争', primary: { traitId: 9, delta: 0.2 } },
    ],
  },
  {
    id: 'ws-r13',
    format: 'ranking',
    prompt: '模型四则',
    promptGloss: '「简洁、准确、普适、可证」── 科学模型，何者最贵？',
    options: [
      { text: '简洁为上', gloss: '奥卡姆剃刀', primary: { traitId: 3, delta: -0.6 } },
      { text: '准确为要', gloss: '与观测高度吻合', primary: { traitId: 3, delta: 0.8 } },
      { text: '普适为先', gloss: '适用范围广泛', primary: { traitId: 3, delta: 0.4 } },
      { text: '可证为基', gloss: '能够被证伪', primary: { traitId: 3, delta: 1.2 } },
      { text: '四者并重', gloss: '均衡为上', primary: { traitId: 3, delta: 0.0 } },
      { text: '以用为归', gloss: '实用最为要紧', primary: { traitId: 3, delta: 0.2 } },
    ],
  },
  {
    id: 'ws-a14',
    format: 'aesthetic',
    prompt: '精密齿轮与自然混沌',
    promptGloss: '精密齿轮之秩序与自然混沌之随机，两种宇宙图景，何者更美？',
    options: [
      { text: '前者', gloss: '前者更合心意', primary: { traitId: 1, delta: 1.2 } },
      { text: '偏前者', gloss: '略偏前者之境', primary: { traitId: 1, delta: 0.6 }, secondary: [{ traitId: 6, delta: 0.2 }] },
      { text: '兼爱之', gloss: '两种意境皆有可取', primary: { traitId: 1, delta: 0.0 }, secondary: [{ traitId: 6, delta: 0.3 }] },
      { text: '偏后者', gloss: '略偏后者之境', primary: { traitId: 1, delta: -0.6 }, secondary: [{ traitId: 6, delta: -0.2 }] },
      { text: '后者', gloss: '后者更入君心', primary: { traitId: 1, delta: -1.2 } },
      { text: '皆不取', gloss: '超乎二者之外', primary: { traitId: 1, delta: -1.4 }, secondary: [{ traitId: 1, delta: 0.2 }] },
    ],
  },
  {
    id: 'ws-053',
    format: 'situational',
    prompt: '经费告罄与成果在望',
    promptGloss: '研究到了最关键的时刻，但经费已经耗尽，眼看即将突破的成果就要中止，你如何选择？',
    options: [
      { text: '倾尽积蓄', gloss: '自掏腰包继续研究', primary: { traitId: 7, delta: 1.4 }, secondary: [{ traitId: 11, delta: 0.3 }] },
      { text: '寻求资助', gloss: '积极申请新经费', primary: { traitId: 3, delta: 0.6 } },
      { text: '缩减范围', gloss: '缩小目标先出成果', primary: { traitId: 1, delta: 0.2 } },
      { text: '公布初步', gloss: '先公布已有发现', primary: { traitId: 5, delta: -0.4 } },
      { text: '放弃研究', gloss: '无奈放弃，另起炉灶', primary: { traitId: 2, delta: -1.4 } },
      { text: '寻求合作', gloss: '找机构与个人合作', primary: { traitId: 5, delta: 0.4 } },
    ],
  },
  {
    id: 'ws-054',
    format: 'imagery',
    prompt: '显微镜下',
    promptGloss: '透过显微镜，看见了一个肉眼从未见过的微观世界，你心中最深的感触是什么？',
    options: [
      { text: '别有洞天', gloss: '一沙一世界', primary: { traitId: 1, delta: 0.8 } },
      { text: '万物同源', gloss: '微观之中有宏观之理', primary: { traitId: 8, delta: 0.6 } },
      { text: '精巧绝伦', gloss: '造物之巧令人叹服', primary: { traitId: 6, delta: 0.4 } },
      { text: '未知无限', gloss: '可知者愈多，未知者愈多', primary: { traitId: 2, delta: 0.8 } },
      { text: '实用之思', gloss: '此发现何日能为世用', primary: { traitId: 10, delta: -0.4 } },
      { text: '习以为常', gloss: '不过日常所见景像', primary: { traitId: 3, delta: -0.6 } },
    ],
  },
  {
    id: 'ws-r14',
    format: 'ranking',
    prompt: '科研四德',
    promptGloss: '「严谨、创新、坚韧、合作」── 科研之德，何者最重？',
    options: [
      { text: '严谨为本', gloss: '求真是第一原则', primary: { traitId: 12, delta: 0.6 } },
      { text: '创新为上', gloss: '突破陈规为要', primary: { traitId: 12, delta: 1.0 } },
      { text: '坚韧为重', gloss: '不达目的不罢休', primary: { traitId: 12, delta: 0.8 } },
      { text: '合作为基', gloss: '独木难成林', primary: { traitId: 12, delta: -0.4 } },
      { text: '四德兼备', gloss: '缺一不可', primary: { traitId: 12, delta: 0.0 } },
      { text: '因时取舍', gloss: '视阶段而择', primary: { traitId: 12, delta: 0.4 } },
    ],
  },
  {
    id: 'ws-a13',
    format: 'aesthetic',
    prompt: '公式对称与自然界图腾',
    promptGloss: '公式对称之优雅与自然界图腾之神秘，两种秩序之美，何者更动人？',
    options: [
      { text: '前者', gloss: '前者更合心意', primary: { traitId: 8, delta: 1.2 } },
      { text: '偏前者', gloss: '略偏前者之境', primary: { traitId: 8, delta: 0.6 }, secondary: [{ traitId: 6, delta: 0.2 }] },
      { text: '兼爱之', gloss: '两种意境皆有可取', primary: { traitId: 8, delta: 0.0 }, secondary: [{ traitId: 6, delta: 0.3 }] },
      { text: '偏后者', gloss: '略偏后者之境', primary: { traitId: 8, delta: -0.6 }, secondary: [{ traitId: 6, delta: -0.2 }] },
      { text: '后者', gloss: '后者更入君心', primary: { traitId: 8, delta: -1.2 } },
      { text: '皆不取', gloss: '超乎二者之外', primary: { traitId: 8, delta: -1.4 }, secondary: [{ traitId: 1, delta: 0.2 }] },
    ],
  },
  {
    id: 'ws-r15',
    format: 'ranking',
    prompt: '发现之途',
    promptGloss: '「灵感、推演、偶然、坚持」── 发现之途，何者最关键？',
    options: [
      { text: '灵感为火', gloss: '灵光一现为始', primary: { traitId: 1, delta: 0.2 } },
      { text: '推演为路', gloss: '逻辑推演为本', primary: { traitId: 1, delta: 0.8 } },
      { text: '偶然为门', gloss: '幸运眷顾有准备的人', primary: { traitId: 1, delta: -0.4 } },
      { text: '坚持为归', gloss: '不放弃是最后的钥匙', primary: { traitId: 1, delta: 1.2 } },
      { text: '四者兼备', gloss: '缺一不可', primary: { traitId: 1, delta: 0.0 } },
      { text: '以勤补拙', gloss: '勤能补拙', primary: { traitId: 1, delta: -0.8 } },
    ],
  },
  {
    id: 'ws-a14',
    format: 'aesthetic',
    prompt: '万有引力与量子涨落',
    promptGloss: '万有引力之宏阔与量子涨落之玄微，两种科学图景，何者更令你心折？',
    options: [
      { text: '前者', gloss: '前者更合心意', primary: { traitId: 4, delta: 1.2 } },
      { text: '偏前者', gloss: '略偏前者之境', primary: { traitId: 4, delta: 0.6 }, secondary: [{ traitId: 6, delta: 0.2 }] },
      { text: '兼爱之', gloss: '两种意境皆有可取', primary: { traitId: 4, delta: 0.0 }, secondary: [{ traitId: 6, delta: 0.3 }] },
      { text: '偏后者', gloss: '略偏后者之境', primary: { traitId: 4, delta: -0.6 }, secondary: [{ traitId: 6, delta: -0.2 }] },
      { text: '后者', gloss: '后者更入君心', primary: { traitId: 4, delta: -1.2 } },
      { text: '皆不取', gloss: '超乎二者之外', primary: { traitId: 4, delta: -1.4 }, secondary: [{ traitId: 1, delta: 0.2 }] },
    ],
  },
];
