// 镜心 · 东方文人墨客 · 48 题
//
// 分布：12 维 × 4 题 = 48 题
// 每题 6 选项，主测一维，副影响 1-2 维
// delta 范围：主 ±1.5，副 ±0.5

import type { Item } from './item.types';

export const ITEMS_EAST_LITERATI: readonly Item[] = [
  // ── T1 思辨 ── 4 题
  {
    id: 'el-001',
    format: 'situational',
    prompt: '夜读有疑，不得其解',
    promptGloss: '深夜读一书，疑而难通，汝当如何？',
    options: [
      {
        text: '搁书而眠',
        gloss: '不急于求通',
        primary: { traitId: 1, delta: -1.2 },
        secondary: [{ traitId: 9, delta: -0.3 }],
      },
      { text: '退而求其次', gloss: '先记其要', primary: { traitId: 1, delta: -0.6 } },
      {
        text: '广引旁证',
        gloss: '参以他书',
        primary: { traitId: 1, delta: 0.4 },
        secondary: [{ traitId: 8, delta: 0.4 }],
      },
      {
        text: '穷其本末',
        gloss: '一路追问到底',
        primary: { traitId: 1, delta: 1.2 },
        secondary: [{ traitId: 8, delta: 0.4 }],
      },
      {
        text: '叩问师友',
        gloss: '以人印证',
        primary: { traitId: 1, delta: 0.2 },
        secondary: [{ traitId: 5, delta: 0.3 }],
      },
      {
        text: '形而上之',
        gloss: '由迹入道',
        primary: { traitId: 1, delta: 1.4 },
        secondary: [{ traitId: 9, delta: 0.4 }],
      },
    ],
  },
  {
    id: 'el-002',
    format: 'imagery',
    prompt: '观山与观水',
    promptGloss: '登山与临水，汝更倾心于何？',
    options: [
      {
        text: '山',
        gloss: '稳而可依',
        primary: { traitId: 1, delta: 0.4 },
        secondary: [{ traitId: 7, delta: 0.3 }],
      },
      {
        text: '水',
        gloss: '流而可变',
        primary: { traitId: 1, delta: -0.3 },
        secondary: [{ traitId: 11, delta: 0.3 }],
      },
      {
        text: '云山',
        gloss: '形而上之象',
        primary: { traitId: 1, delta: 1.3 },
        secondary: [{ traitId: 6, delta: 0.5 }],
      },
      { text: '溪涧', gloss: '理在寻常', primary: { traitId: 1, delta: -1.0 } },
      {
        text: '海',
        gloss: '深而难测',
        primary: { traitId: 1, delta: 1.0 },
        secondary: [{ traitId: 10, delta: 0.4 }],
      },
      { text: '丘', gloss: '不山不水', primary: { traitId: 1, delta: -0.2 } },
    ],
  },
  {
    id: 'el-003',
    format: 'aesthetic',
    prompt: '「道可道，非常道」',
    promptGloss: '对此语，汝所感最深者何？',
    options: [
      {
        text: '言之不尽',
        gloss: '以言障意',
        primary: { traitId: 1, delta: 1.2 },
        secondary: [{ traitId: 12, delta: -0.3 }],
      },
      { text: '知其然即可', gloss: '不必穷理', primary: { traitId: 1, delta: -1.0 } },
      { text: '可道者非道', gloss: '道在言外', primary: { traitId: 1, delta: 1.3 } },
      { text: '常道亦道', gloss: '执两用中', primary: { traitId: 1, delta: 0.2 } },
      { text: '此玄谈耳', gloss: '不切实用', primary: { traitId: 1, delta: -1.3 } },
      { text: '言之即是', gloss: '以言为道', primary: { traitId: 1, delta: -0.6 } },
    ],
  },
  {
    id: 'el-004',
    format: 'ranking',
    prompt: '四事，汝心中最重者',
    promptGloss: '「理、情、势、术」── 汝最重何？',
    options: [
      { text: '理', gloss: '以理为尊', primary: { traitId: 1, delta: 1.4 } },
      {
        text: '情',
        gloss: '以情为真',
        primary: { traitId: 1, delta: -0.4 },
        secondary: [{ traitId: 2, delta: 0.5 }],
      },
      {
        text: '势',
        gloss: '以势为用',
        primary: { traitId: 1, delta: -0.8 },
        secondary: [{ traitId: 3, delta: 0.4 }],
      },
      {
        text: '术',
        gloss: '以术为巧',
        primary: { traitId: 1, delta: -1.0 },
        secondary: [{ traitId: 3, delta: 0.3 }],
      },
      { text: '皆重', gloss: '不偏于一边', primary: { traitId: 1, delta: 0.2 } },
      { text: '皆轻', gloss: '随事而行', primary: { traitId: 1, delta: -0.5 } },
    ],
  },

  // ── T2 情感 ── 4 题
  {
    id: 'el-005',
    format: 'situational',
    prompt: '挚友远行',
    promptGloss: '至交远赴千里，汝当如何？',
    options: [
      { text: '临别无语', gloss: '默默以送', primary: { traitId: 2, delta: -1.2 } },
      {
        text: '赋诗一首',
        gloss: '以诗代语',
        primary: { traitId: 2, delta: 0.8 },
        secondary: [{ traitId: 12, delta: 0.4 }],
      },
      { text: '挥泪相送', gloss: '情不掩于形', primary: { traitId: 2, delta: 1.4 } },
      { text: '赠一薄物', gloss: '以物托意', primary: { traitId: 2, delta: 0.2 } },
      { text: '托人问候', gloss: '不远送', primary: { traitId: 2, delta: -0.6 } },
      {
        text: '与之同歌',
        gloss: '以歌送行',
        primary: { traitId: 2, delta: 1.2 },
        secondary: [{ traitId: 6, delta: 0.4 }],
      },
    ],
  },
  {
    id: 'el-006',
    format: 'imagery',
    prompt: '春与秋',
    promptGloss: '春与秋，汝更爱何季？',
    options: [
      {
        text: '春',
        gloss: '喜生发之机',
        primary: { traitId: 2, delta: 1.2 },
        secondary: [{ traitId: 6, delta: 0.4 }],
      },
      { text: '秋', gloss: '喜收敛之静', primary: { traitId: 2, delta: -0.6 } },
      { text: '皆爱', gloss: '随四时之序', primary: { traitId: 2, delta: 0.0 } },
      { text: '皆不爱', gloss: '任其所至', primary: { traitId: 2, delta: -1.0 } },
      {
        text: '夏',
        gloss: '喜热烈之盛',
        primary: { traitId: 2, delta: 0.8 },
        secondary: [{ traitId: 9, delta: 0.3 }],
      },
      { text: '冬', gloss: '喜静穆之深', primary: { traitId: 2, delta: -0.8 } },
    ],
  },
  {
    id: 'el-007',
    format: 'aesthetic',
    prompt: '「悲莫悲兮生别离」',
    promptGloss: '对此句，汝所感最深者何？',
    options: [
      { text: '悲', gloss: '以悲为情之极', primary: { traitId: 2, delta: 1.4 } },
      { text: '别', gloss: '以离为人生常态', primary: { traitId: 2, delta: 0.6 } },
      {
        text: '生',
        gloss: '以生为可贵',
        primary: { traitId: 2, delta: -0.4 },
        secondary: [{ traitId: 1, delta: 0.4 }],
      },
      { text: '此情之常', gloss: '不必悲', primary: { traitId: 2, delta: -1.2 } },
      { text: '此情之痛', gloss: '痛之深也', primary: { traitId: 2, delta: 1.0 } },
      { text: '无言', gloss: '情至无言', primary: { traitId: 2, delta: -0.6 } },
    ],
  },
  {
    id: 'el-008',
    format: 'situational',
    prompt: '闻人死讯',
    promptGloss: '闻一相识者逝，汝当如何？',
    options: [
      { text: '恸哭一场', gloss: '以哭为怀', primary: { traitId: 2, delta: 1.4 } },
      { text: '静坐默哀', gloss: '以静为怀', primary: { traitId: 2, delta: -0.6 } },
      {
        text: '作一文以祭',
        gloss: '以文为怀',
        primary: { traitId: 2, delta: 0.4 },
        secondary: [{ traitId: 12, delta: 0.4 }],
      },
      {
        text: '为身后事奔走',
        gloss: '以行为怀',
        primary: { traitId: 2, delta: -1.0 },
        secondary: [{ traitId: 3, delta: 0.4 }],
      },
      { text: '不以为意', gloss: '以理观之', primary: { traitId: 2, delta: -1.3 } },
      { text: '托人致唁', gloss: '以礼为怀', primary: { traitId: 2, delta: -0.2 } },
    ],
  },

  // ── T3 行动 ── 4 题
  {
    id: 'el-009',
    format: 'situational',
    prompt: '事有可为',
    promptGloss: '见一事可为，汝当如何？',
    options: [
      { text: '即刻行之', gloss: '雷厉风行', primary: { traitId: 3, delta: 1.4 } },
      {
        text: '审而后动',
        gloss: '三思后行',
        primary: { traitId: 3, delta: -0.8 },
        secondary: [{ traitId: 7, delta: 0.3 }],
      },
      {
        text: '与人共议',
        gloss: '借众而行',
        primary: { traitId: 3, delta: 0.4 },
        secondary: [{ traitId: 5, delta: 0.4 }],
      },
      {
        text: '先观其势',
        gloss: '以待天时',
        primary: { traitId: 3, delta: -1.0 },
        secondary: [{ traitId: 11, delta: -0.3 }],
      },
      {
        text: '躬自任之',
        gloss: '以身为任',
        primary: { traitId: 3, delta: 1.0 },
        secondary: [{ traitId: 7, delta: 0.3 }],
      },
      { text: '不为之', gloss: '非所当为', primary: { traitId: 3, delta: -1.4 } },
    ],
  },
  {
    id: 'el-010',
    format: 'imagery',
    prompt: '剑与箫',
    promptGloss: '剑与箫，汝更爱何器？',
    options: [
      {
        text: '剑',
        gloss: '以利为器',
        primary: { traitId: 3, delta: 1.2 },
        secondary: [{ traitId: 7, delta: 0.3 }],
      },
      {
        text: '箫',
        gloss: '以声为器',
        primary: { traitId: 3, delta: -1.0 },
        secondary: [{ traitId: 6, delta: 0.5 }],
      },
      {
        text: '笔',
        gloss: '以言为器',
        primary: { traitId: 3, delta: 0.0 },
        secondary: [{ traitId: 12, delta: 0.5 }],
      },
      { text: '琴', gloss: '以和为器', primary: { traitId: 3, delta: -0.6 } },
      {
        text: '弓',
        gloss: '以射为器',
        primary: { traitId: 3, delta: 1.0 },
        secondary: [{ traitId: 11, delta: 0.3 }],
      },
      { text: '皆不取', gloss: '以无为器', primary: { traitId: 3, delta: -1.3 } },
    ],
  },
  {
    id: 'el-011',
    format: 'aesthetic',
    prompt: '「知而行之」',
    promptGloss: '知而不行，汝以为然否？',
    options: [
      { text: '知必行', gloss: '以行践知', primary: { traitId: 3, delta: 1.4 } },
      { text: '知难行', gloss: '知易行难', primary: { traitId: 3, delta: -0.6 } },
      { text: '行先于知', gloss: '不知而行', primary: { traitId: 3, delta: 0.6 } },
      { text: '知不必然行', gloss: '知为知也', primary: { traitId: 3, delta: -1.2 } },
      { text: '知行合一', gloss: '不分彼此', primary: { traitId: 3, delta: 0.2 } },
      { text: '行难知更难', gloss: '以知为先', primary: { traitId: 3, delta: -0.8 } },
    ],
  },
  {
    id: 'el-012',
    format: 'situational',
    prompt: '民有疾苦',
    promptGloss: '闻民间疾苦，汝当如何？',
    options: [
      {
        text: '上书直陈',
        gloss: '以言为政',
        primary: { traitId: 3, delta: 0.4 },
        secondary: [{ traitId: 4, delta: 0.3 }],
      },
      { text: '躬身救助', gloss: '以身为政', primary: { traitId: 3, delta: 1.3 } },
      {
        text: '聚众议事',
        gloss: '以众为政',
        primary: { traitId: 3, delta: 0.6 },
        secondary: [{ traitId: 5, delta: 0.4 }],
      },
      { text: '默而记之', gloss: '以史为政', primary: { traitId: 3, delta: -1.0 } },
      { text: '托友代办', gloss: '以人为政', primary: { traitId: 3, delta: -0.4 } },
      { text: '不以为意', gloss: '以远为政', primary: { traitId: 3, delta: -1.4 } },
    ],
  },

  // ── T4 革新 ── 4 题
  {
    id: 'el-013',
    format: 'situational',
    prompt: '古制已坏',
    promptGloss: '见古制已坏，汝当如何？',
    options: [
      { text: '复其旧制', gloss: '以复古为新', primary: { traitId: 4, delta: -1.4 } },
      { text: '修其残缺', gloss: '以修补为新', primary: { traitId: 4, delta: -0.6 } },
      { text: '因时损益', gloss: '以中道为新', primary: { traitId: 4, delta: 0.0 } },
      { text: '另立新制', gloss: '以破立为新', primary: { traitId: 4, delta: 1.2 } },
      {
        text: '悉数推倒',
        gloss: '以革命为新',
        primary: { traitId: 4, delta: 1.4 },
        secondary: [{ traitId: 7, delta: 0.3 }],
      },
      { text: '不置可否', gloss: '以不议为新', primary: { traitId: 4, delta: -0.8 } },
    ],
  },
  {
    id: 'el-014',
    format: 'ranking',
    prompt: '四字，汝最重',
    promptGloss: '「守、变、破、立」── 汝最重何？',
    options: [
      { text: '守', gloss: '以守为立', primary: { traitId: 4, delta: -1.4 } },
      { text: '变', gloss: '以变为常', primary: { traitId: 4, delta: 0.4 } },
      { text: '破', gloss: '以破为快', primary: { traitId: 4, delta: 1.2 } },
      {
        text: '立',
        gloss: '以立为功',
        primary: { traitId: 4, delta: 0.8 },
        secondary: [{ traitId: 3, delta: 0.4 }],
      },
      { text: '守破之间', gloss: '执两用中', primary: { traitId: 4, delta: -0.2 } },
      { text: '破立相生', gloss: '以破为立', primary: { traitId: 4, delta: 1.4 } },
    ],
  },
  {
    id: 'el-015',
    format: 'aesthetic',
    prompt: '「天变不足畏」',
    promptGloss: '对此言，汝所感最深者何？',
    options: [
      {
        text: '敢',
        gloss: '以敢为气',
        primary: { traitId: 4, delta: 1.4 },
        secondary: [{ traitId: 11, delta: 0.3 }],
      },
      { text: '狂', gloss: '以狂为病', primary: { traitId: 4, delta: 0.4 } },
      { text: '慎', gloss: '以慎为德', primary: { traitId: 4, delta: -1.0 } },
      { text: '信', gloss: '以信为基', primary: { traitId: 4, delta: -0.6 } },
      {
        text: '智',
        gloss: '以智为刃',
        primary: { traitId: 4, delta: 0.6 },
        secondary: [{ traitId: 1, delta: 0.4 }],
      },
      { text: '仁', gloss: '以仁为本', primary: { traitId: 4, delta: -1.4 } },
    ],
  },
  {
    id: 'el-016',
    format: 'imagery',
    prompt: '种子与根',
    promptGloss: '种子与根，汝更爱何？',
    options: [
      { text: '种子', gloss: '以始为重', primary: { traitId: 4, delta: 1.2 } },
      { text: '根', gloss: '以本为重', primary: { traitId: 4, delta: -1.0 } },
      { text: '苗', gloss: '以生为重', primary: { traitId: 4, delta: 0.4 } },
      { text: '花', gloss: '以显为重', primary: { traitId: 4, delta: 0.0 } },
      { text: '果', gloss: '以成实为重', primary: { traitId: 4, delta: -0.4 } },
      { text: '土', gloss: '以厚为重', primary: { traitId: 4, delta: -1.2 } },
    ],
  },

  // ── T5 群我 ── 4 题
  {
    id: 'el-017',
    format: 'situational',
    prompt: '群议有违',
    promptGloss: '众人之议与己见相左，汝当如何？',
    options: [
      {
        text: '从众',
        gloss: '以和为贵',
        primary: { traitId: 5, delta: 1.0 },
        secondary: [{ traitId: 7, delta: -0.4 }],
      },
      { text: '直言己见', gloss: '以直为真', primary: { traitId: 5, delta: -1.0 } },
      { text: '折中调和', gloss: '以中为用', primary: { traitId: 5, delta: 0.4 } },
      { text: '退而不争', gloss: '以退为进', primary: { traitId: 5, delta: 0.8 } },
      {
        text: '引经据典',
        gloss: '以理服人',
        primary: { traitId: 5, delta: -0.4 },
        secondary: [{ traitId: 1, delta: 0.4 }],
      },
      { text: '议而不决', gloss: '以不议为议', primary: { traitId: 5, delta: 0.0 } },
    ],
  },
  {
    id: 'el-018',
    format: 'ranking',
    prompt: '四者之先',
    promptGloss: '「己、家、国、天下」── 汝最重何？',
    options: [
      { text: '己', gloss: '以身为先', primary: { traitId: 5, delta: -1.4 } },
      { text: '家', gloss: '以家为先', primary: { traitId: 5, delta: -0.6 } },
      { text: '国', gloss: '以国为先', primary: { traitId: 5, delta: 0.4 } },
      { text: '天下', gloss: '以天下为先', primary: { traitId: 5, delta: 1.4 } },
      { text: '己家并重', gloss: '以近为远', primary: { traitId: 5, delta: -0.8 } },
      { text: '国天同重', gloss: '以远为近', primary: { traitId: 5, delta: 1.0 } },
    ],
  },
  {
    id: 'el-019',
    format: 'aesthetic',
    prompt: '「独善其身」',
    promptGloss: '对此语，汝所感最深者何？',
    options: [
      { text: '善', gloss: '以善为志', primary: { traitId: 5, delta: -0.4 } },
      { text: '独', gloss: '以独为高', primary: { traitId: 5, delta: -1.2 } },
      { text: '身', gloss: '以身为贵', primary: { traitId: 5, delta: -0.8 } },
      { text: '兼善', gloss: '善及于众', primary: { traitId: 5, delta: 1.4 } },
      { text: '先独后兼', gloss: '以独为基', primary: { traitId: 5, delta: 0.2 } },
      { text: '先兼后独', gloss: '以兼为基', primary: { traitId: 5, delta: 0.8 } },
    ],
  },
  {
    id: 'el-020',
    format: 'imagery',
    prompt: '孤峰与众山',
    promptGloss: '孤峰与众山，汝更倾何？',
    options: [
      { text: '孤峰', gloss: '以独立为美', primary: { traitId: 5, delta: -1.2 } },
      { text: '众山', gloss: '以连绵为美', primary: { traitId: 5, delta: 1.0 } },
      { text: '远山', gloss: '以相望为美', primary: { traitId: 5, delta: 0.2 } },
      { text: '丘壑', gloss: '以错落为美', primary: { traitId: 5, delta: 0.4 } },
      { text: '平川', gloss: '以开阔为美', primary: { traitId: 5, delta: 0.6 } },
      { text: '天际', gloss: '以无我为美', primary: { traitId: 5, delta: -0.4 } },
    ],
  },

  // ── T6 审美 ── 4 题
  {
    id: 'el-021',
    format: 'imagery',
    prompt: '工笔与写意',
    promptGloss: '工笔之细与写意之放，汝更爱何？',
    options: [
      { text: '工笔', gloss: '以工为美', primary: { traitId: 6, delta: -1.0 } },
      { text: '写意', gloss: '以意为美', primary: { traitId: 6, delta: 1.4 } },
      { text: '兼工', gloss: '以工意相生为美', primary: { traitId: 6, delta: 0.0 } },
      { text: '白描', gloss: '以素为美', primary: { traitId: 6, delta: -0.6 } },
      { text: '泼墨', gloss: '以放为美', primary: { traitId: 6, delta: 1.0 } },
      { text: '设色', gloss: '以艳为美', primary: { traitId: 6, delta: 0.4 } },
    ],
  },
  {
    id: 'el-022',
    format: 'aesthetic',
    prompt: '「大音希声」',
    promptGloss: '对此语，汝所感最深者何？',
    options: [
      { text: '希', gloss: '以稀为美', primary: { traitId: 6, delta: 1.4 } },
      { text: '大', gloss: '以大为美', primary: { traitId: 6, delta: 0.6 } },
      { text: '声', gloss: '以声为美', primary: { traitId: 6, delta: -0.8 } },
      { text: '无', gloss: '以无有为美', primary: { traitId: 6, delta: 1.2 } },
      { text: '有', gloss: '以有形为美', primary: { traitId: 6, delta: -1.2 } },
      { text: '中和', gloss: '以中为美', primary: { traitId: 6, delta: -0.2 } },
    ],
  },
  {
    id: 'el-023',
    format: 'ranking',
    prompt: '四韵，汝最倾',
    promptGloss: '「清、丽、雅、雄」── 汝最倾何？',
    options: [
      { text: '清', gloss: '以清为上', primary: { traitId: 6, delta: 1.0 } },
      { text: '丽', gloss: '以丽为上', primary: { traitId: 6, delta: 0.4 } },
      { text: '雅', gloss: '以雅为上', primary: { traitId: 6, delta: 0.8 } },
      {
        text: '雄',
        gloss: '以雄为上',
        primary: { traitId: 6, delta: -0.4 },
        secondary: [{ traitId: 7, delta: 0.3 }],
      },
      { text: '皆可', gloss: '随境而取', primary: { traitId: 6, delta: -0.8 } },
      { text: '皆不可', gloss: '以无韵为韵', primary: { traitId: 6, delta: -1.2 } },
    ],
  },
  {
    id: 'el-024',
    format: 'imagery',
    prompt: '梅与牡丹',
    promptGloss: '梅与牡丹，汝更爱何？',
    options: [
      {
        text: '梅',
        gloss: '以瘦为美',
        primary: { traitId: 6, delta: 1.0 },
        secondary: [{ traitId: 7, delta: 0.3 }],
      },
      { text: '牡丹', gloss: '以盛为美', primary: { traitId: 6, delta: -0.6 } },
      { text: '兰', gloss: '以幽为美', primary: { traitId: 6, delta: 1.2 } },
      { text: '菊', gloss: '以淡为美', primary: { traitId: 6, delta: 0.8 } },
      { text: '荷', gloss: '以洁为美', primary: { traitId: 6, delta: 0.6 } },
      { text: '皆爱', gloss: '随时序赏', primary: { traitId: 6, delta: -0.8 } },
    ],
  },

  // ── T7 意志 ── 4 题
  {
    id: 'el-025',
    format: 'situational',
    prompt: '困于逆境',
    promptGloss: '身处逆境，汝当如何？',
    options: [
      { text: '刚强不屈', gloss: '以刚克难', primary: { traitId: 7, delta: 1.4 } },
      { text: '顺其自然', gloss: '以柔克难', primary: { traitId: 7, delta: -1.0 } },
      {
        text: '隐忍以图',
        gloss: '以待时变',
        primary: { traitId: 7, delta: -0.4 },
        secondary: [{ traitId: 11, delta: -0.3 }],
      },
      { text: '以死抗争', gloss: '以死明志', primary: { traitId: 7, delta: 1.2 } },
      { text: '远走避祸', gloss: '以远为安', primary: { traitId: 7, delta: -1.2 } },
      {
        text: '与人共济',
        gloss: '以众为力',
        primary: { traitId: 7, delta: 0.4 },
        secondary: [{ traitId: 5, delta: 0.4 }],
      },
    ],
  },
  {
    id: 'el-026',
    format: 'aesthetic',
    prompt: '「宁折不弯」',
    promptGloss: '对此语，汝所感最深者何？',
    options: [
      { text: '折', gloss: '以折为正', primary: { traitId: 7, delta: 1.4 } },
      { text: '弯', gloss: '以弯为智', primary: { traitId: 7, delta: -1.4 } },
      { text: '折弯相宜', gloss: '随时为变', primary: { traitId: 7, delta: 0.0 } },
      { text: '不折不弯', gloss: '以中为行', primary: { traitId: 7, delta: -0.4 } },
      { text: '宁弯亦存', gloss: '以存为上', primary: { traitId: 7, delta: -1.0 } },
      { text: '宁折不存', gloss: '以义为上', primary: { traitId: 7, delta: 1.2 } },
    ],
  },
  {
    id: 'el-027',
    format: 'imagery',
    prompt: '石与水',
    promptGloss: '石与水，汝更爱何？',
    options: [
      { text: '石', gloss: '以坚为德', primary: { traitId: 7, delta: 1.2 } },
      { text: '水', gloss: '以柔为德', primary: { traitId: 7, delta: -1.2 } },
      { text: '山', gloss: '以重为德', primary: { traitId: 7, delta: 0.8 } },
      { text: '风', gloss: '以动为德', primary: { traitId: 7, delta: 0.2 } },
      { text: '云', gloss: '以散为德', primary: { traitId: 7, delta: -0.6 } },
      { text: '土', gloss: '以厚为德', primary: { traitId: 7, delta: 0.4 } },
    ],
  },
  {
    id: 'el-028',
    format: 'situational',
    prompt: '有辱加身',
    promptGloss: '受辱于众，汝当如何？',
    options: [
      { text: '拔剑而起', gloss: '以血还辱', primary: { traitId: 7, delta: 1.4 } },
      { text: '忍而不发', gloss: '以忍为勇', primary: { traitId: 7, delta: -0.6 } },
      { text: '一笑置之', gloss: '以笑化辱', primary: { traitId: 7, delta: -1.0 } },
      { text: '事后以功明', gloss: '以行洗辱', primary: { traitId: 7, delta: 0.4 } },
      { text: '托人辩白', gloss: '以言解辱', primary: { traitId: 7, delta: -0.4 } },
      { text: '自省其过', gloss: '以省为善', primary: { traitId: 7, delta: -0.8 } },
    ],
  },

  // ── T8 学识 ── 4 题
  {
    id: 'el-029',
    format: 'ranking',
    prompt: '四部，汝最重',
    promptGloss: '「经、史、子、集」── 汝最重何？',
    options: [
      { text: '经', gloss: '以经为尊', primary: { traitId: 8, delta: 0.6 } },
      {
        text: '史',
        gloss: '以史为鉴',
        primary: { traitId: 8, delta: 0.2 },
        secondary: [{ traitId: 10, delta: 0.4 }],
      },
      { text: '子', gloss: '以子为思', primary: { traitId: 8, delta: 0.8 } },
      {
        text: '集',
        gloss: '以集为情',
        primary: { traitId: 8, delta: -0.6 },
        secondary: [{ traitId: 2, delta: 0.4 }],
      },
      { text: '皆读', gloss: '以博为学', primary: { traitId: 8, delta: -1.0 } },
      { text: '专一', gloss: '以专为学', primary: { traitId: 8, delta: 1.0 } },
    ],
  },
  {
    id: 'el-030',
    format: 'situational',
    prompt: '学有未通',
    promptGloss: '一学未通，汝当如何？',
    options: [
      { text: '穷研十年', gloss: '以深为功', primary: { traitId: 8, delta: 1.4 } },
      { text: '广取他学', gloss: '以博为功', primary: { traitId: 8, delta: -1.0 } },
      { text: '转习他业', gloss: '以变为功', primary: { traitId: 8, delta: -0.6 } },
      { text: '问于师友', gloss: '以人为功', primary: { traitId: 8, delta: -0.2 } },
      { text: '先记其要', gloss: '以要为本', primary: { traitId: 8, delta: 0.4 } },
      { text: '付诸实用', gloss: '以用为归', primary: { traitId: 8, delta: -1.2 } },
    ],
  },
  {
    id: 'el-031',
    format: 'aesthetic',
    prompt: '「吾生也有涯，而知也无涯」',
    promptGloss: '对此语，汝所感最深者何？',
    options: [
      {
        text: '有涯',
        gloss: '以生为限',
        primary: { traitId: 8, delta: -0.6 },
        secondary: [{ traitId: 10, delta: 0.3 }],
      },
      { text: '无涯', gloss: '以知无极', primary: { traitId: 8, delta: 1.4 } },
      { text: '以有涯逐无涯', gloss: '以行殉知', primary: { traitId: 8, delta: 0.8 } },
      { text: '殆已', gloss: '以殆为戒', primary: { traitId: 8, delta: -1.2 } },
      { text: '知止', gloss: '以止为智', primary: { traitId: 8, delta: -0.8 } },
      { text: '知足', gloss: '以足为学', primary: { traitId: 8, delta: -0.4 } },
    ],
  },
  {
    id: 'el-032',
    format: 'imagery',
    prompt: '江与井',
    promptGloss: '江与井，汝更倾何？',
    options: [
      { text: '江', gloss: '以广为学', primary: { traitId: 8, delta: -1.2 } },
      { text: '井', gloss: '以深为学', primary: { traitId: 8, delta: 1.4 } },
      { text: '海', gloss: '以无涯为学', primary: { traitId: 8, delta: 0.6 } },
      { text: '泉', gloss: '以活为学', primary: { traitId: 8, delta: 0.4 } },
      { text: '溪', gloss: '以清为学', primary: { traitId: 8, delta: 0.0 } },
      { text: '湖', gloss: '以静为学', primary: { traitId: 8, delta: -0.4 } },
    ],
  },

  // ── T9 处世 ── 4 题
  {
    id: 'el-033',
    format: 'situational',
    prompt: '时不予我',
    promptGloss: '时运不济，汝当如何？',
    options: [
      { text: '出而行世', gloss: '以出为用', primary: { traitId: 9, delta: 1.0 } },
      { text: '处而自修', gloss: '以处为修', primary: { traitId: 9, delta: -0.8 } },
      { text: '隐而不仕', gloss: '以隐为高', primary: { traitId: 9, delta: -1.4 } },
      { text: '行藏以时', gloss: '以时为度', primary: { traitId: 9, delta: 0.2 } },
      { text: '出而复归', gloss: '以归为终', primary: { traitId: 9, delta: -0.4 } },
      { text: '为而不争', gloss: '以不争为争', primary: { traitId: 9, delta: -0.6 } },
    ],
  },
  {
    id: 'el-034',
    format: 'aesthetic',
    prompt: '「穷则独善其身，达则兼善天下」',
    promptGloss: '对此语，汝所感最深者何？',
    options: [
      { text: '穷', gloss: '以穷为常', primary: { traitId: 9, delta: -0.6 } },
      { text: '达', gloss: '以达为愿', primary: { traitId: 9, delta: 1.0 } },
      { text: '独善', gloss: '以独为正', primary: { traitId: 9, delta: -1.2 } },
      { text: '兼善', gloss: '以兼为怀', primary: { traitId: 9, delta: 1.4 } },
      { text: '穷达皆善', gloss: '以善为常', primary: { traitId: 9, delta: 0.2 } },
      { text: '穷达皆忘', gloss: '以无我为常', primary: { traitId: 9, delta: -0.8 } },
    ],
  },
  {
    id: 'el-035',
    format: 'imagery',
    prompt: '舟与岸',
    promptGloss: '舟与岸，汝更爱何？',
    options: [
      { text: '舟', gloss: '以行为乐', primary: { traitId: 9, delta: 1.4 } },
      { text: '岸', gloss: '以止为安', primary: { traitId: 9, delta: -1.2 } },
      { text: '泊', gloss: '以泊为度', primary: { traitId: 9, delta: -0.2 } },
      { text: '渡', gloss: '以渡为用', primary: { traitId: 9, delta: 0.4 } },
      { text: '灯塔', gloss: '以守为照', primary: { traitId: 9, delta: -0.6 } },
      { text: '云帆', gloss: '以远为志', primary: { traitId: 9, delta: 1.0 } },
    ],
  },
  {
    id: 'el-036',
    format: 'situational',
    prompt: '友有显达',
    promptGloss: '友有显达而己未达，汝当如何？',
    options: [
      { text: '贺而不慕', gloss: '以贺为怀', primary: { traitId: 9, delta: -0.4 } },
      { text: '慕而求进', gloss: '以进为怀', primary: { traitId: 9, delta: 1.0 } },
      { text: '退而自安', gloss: '以退为怀', primary: { traitId: 9, delta: -1.0 } },
      { text: '绝之', gloss: '以绝为怀', primary: { traitId: 9, delta: -1.4 } },
      { text: '随而借势', gloss: '以随为用', primary: { traitId: 9, delta: 0.6 } },
      { text: '不改其常', gloss: '以常为守', primary: { traitId: 9, delta: -0.2 } },
    ],
  },

  // ── T10 时间 ── 4 题
  {
    id: 'el-037',
    format: 'imagery',
    prompt: '朝与暮',
    promptGloss: '朝与暮，汝更爱何时？',
    options: [
      { text: '朝', gloss: '以生为美', primary: { traitId: 10, delta: -0.6 } },
      { text: '暮', gloss: '以归为美', primary: { traitId: 10, delta: 0.8 } },
      { text: '夜', gloss: '以深为美', primary: { traitId: 10, delta: 1.2 } },
      { text: '旦', gloss: '以始为美', primary: { traitId: 10, delta: -1.0 } },
      { text: '午', gloss: '以盛为美', primary: { traitId: 10, delta: -0.4 } },
      { text: '皆爱', gloss: '随时为美', primary: { traitId: 10, delta: 0.0 } },
    ],
  },
  {
    id: 'el-038',
    format: 'situational',
    prompt: '功在千秋',
    promptGloss: '所作可为百世之功，汝愿为之否？',
    options: [
      { text: '愿', gloss: '以远为志', primary: { traitId: 10, delta: 1.4 } },
      { text: '不愿', gloss: '以当世为足', primary: { traitId: 10, delta: -1.0 } },
      { text: '随缘', gloss: '以因缘为度', primary: { traitId: 10, delta: 0.4 } },
      { text: '不必', gloss: '以无为为', primary: { traitId: 10, delta: -0.6 } },
      { text: '为而不居', gloss: '以不居为功', primary: { traitId: 10, delta: 0.8 } },
      { text: '传而不朽', gloss: '以传为愿', primary: { traitId: 10, delta: 1.0 } },
    ],
  },
  {
    id: 'el-039',
    format: 'aesthetic',
    prompt: '「不朽」',
    promptGloss: '对此二字，汝所感最深者何？',
    options: [
      { text: '立言', gloss: '以言为不朽', primary: { traitId: 10, delta: 1.2 } },
      { text: '立德', gloss: '以德为不朽', primary: { traitId: 10, delta: 1.0 } },
      { text: '立功', gloss: '以功为不朽', primary: { traitId: 10, delta: 0.8 } },
      { text: '不必朽', gloss: '以无为不朽', primary: { traitId: 10, delta: -1.0 } },
      { text: '随缘', gloss: '以缘为不朽', primary: { traitId: 10, delta: -0.4 } },
      { text: '立心', gloss: '以心为不朽', primary: { traitId: 10, delta: 1.4 } },
    ],
  },
  {
    id: 'el-040',
    format: 'ranking',
    prompt: '三时，汝最重',
    promptGloss: '「昨日、今日、明日」── 汝最重何？',
    options: [
      { text: '昨日', gloss: '以史为鉴', primary: { traitId: 10, delta: 0.4 } },
      { text: '今日', gloss: '以当为要', primary: { traitId: 10, delta: -0.8 } },
      { text: '明日', gloss: '以远为志', primary: { traitId: 10, delta: 1.4 } },
      { text: '昨日已往', gloss: '以忘为智', primary: { traitId: 10, delta: -0.4 } },
      { text: '今日当行', gloss: '以行为要', primary: { traitId: 10, delta: -1.0 } },
      { text: '明日当期', gloss: '以期为美', primary: { traitId: 10, delta: 0.8 } },
    ],
  },

  // ── T11 风险 ── 4 题
  {
    id: 'el-041',
    format: 'situational',
    prompt: '机不可失',
    promptGloss: '良机一闪即逝，汝当如何？',
    options: [
      { text: '即下决断', gloss: '以断为勇', primary: { traitId: 11, delta: 1.4 } },
      { text: '退而待之', gloss: '以稳为上', primary: { traitId: 11, delta: -1.2 } },
      { text: '半进半退', gloss: '以中为用', primary: { traitId: 11, delta: 0.2 } },
      { text: '与人共议', gloss: '以众为断', primary: { traitId: 11, delta: -0.6 } },
      { text: '观其始末', gloss: '以观为决', primary: { traitId: 11, delta: -0.8 } },
      { text: '舍机取势', gloss: '以势为机', primary: { traitId: 11, delta: 0.6 } },
    ],
  },
  {
    id: 'el-042',
    format: 'imagery',
    prompt: '弈与弈',
    promptGloss: '落子无悔，汝以为如何？',
    options: [
      { text: '无悔', gloss: '以果为上', primary: { traitId: 11, delta: 1.2 } },
      { text: '常悔', gloss: '以慎为上', primary: { traitId: 11, delta: -1.2 } },
      { text: '慎而落', gloss: '以慎为基', primary: { traitId: 11, delta: -0.6 } },
      { text: '落而慎', gloss: '以行慎为要', primary: { traitId: 11, delta: -0.4 } },
      { text: '随棋', gloss: '以随为上', primary: { traitId: 11, delta: 0.4 } },
      { text: '不落', gloss: '以不落为上', primary: { traitId: 11, delta: -0.8 } },
    ],
  },
  {
    id: 'el-043',
    format: 'aesthetic',
    prompt: '「不入虎穴，焉得虎子」',
    promptGloss: '对此语，汝所感最深者何？',
    options: [
      { text: '虎穴', gloss: '以险为功', primary: { traitId: 11, delta: 1.4 } },
      { text: '虎子', gloss: '以得为愿', primary: { traitId: 11, delta: 0.6 } },
      { text: '不入', gloss: '以不入为智', primary: { traitId: 11, delta: -1.4 } },
      { text: '入而不执', gloss: '以入为度', primary: { traitId: 11, delta: 0.0 } },
      { text: '入而有备', gloss: '以备为上', primary: { traitId: 11, delta: -0.6 } },
      { text: '不入亦得', gloss: '以不取为取', primary: { traitId: 11, delta: -0.8 } },
    ],
  },
  {
    id: 'el-044',
    format: 'situational',
    prompt: '国难临头',
    promptGloss: '国难临头，汝当如何？',
    options: [
      { text: '赴难如归', gloss: '以身殉国', primary: { traitId: 11, delta: 1.4 } },
      { text: '避地远祸', gloss: '以远为安', primary: { traitId: 11, delta: -1.4 } },
      { text: '隐于山林', gloss: '以隐为正', primary: { traitId: 11, delta: -0.8 } },
      { text: '从众以避', gloss: '以众为用', primary: { traitId: 11, delta: -0.4 } },
      { text: '暗中图复', gloss: '以暗为谋', primary: { traitId: 11, delta: 0.4 } },
      { text: '待时而起', gloss: '以时为断', primary: { traitId: 11, delta: 0.6 } },
    ],
  },

  // ── T12 表达 ── 4 题
  {
    id: 'el-045',
    format: 'imagery',
    prompt: '白与文',
    promptGloss: '白话与文言，汝更倾何？',
    options: [
      { text: '白话', gloss: '以俗为真', primary: { traitId: 12, delta: -1.4 } },
      { text: '文言', gloss: '以雅为美', primary: { traitId: 12, delta: 1.4 } },
      { text: '半文半白', gloss: '以中为用', primary: { traitId: 12, delta: 0.0 } },
      { text: '口语', gloss: '以口为真', primary: { traitId: 12, delta: -1.0 } },
      { text: '诗语', gloss: '以诗为美', primary: { traitId: 12, delta: 1.0 } },
      { text: '皆不可', gloss: '以无言为上', primary: { traitId: 12, delta: -0.6 } },
    ],
  },
  {
    id: 'el-046',
    format: 'situational',
    prompt: '欲言又止',
    promptGloss: '言有未尽，汝当如何？',
    options: [
      { text: '书以代之', gloss: '以书为言', primary: { traitId: 12, delta: 0.6 } },
      { text: '歌以咏之', gloss: '以歌为言', primary: { traitId: 12, delta: 1.2 } },
      { text: '画以形之', gloss: '以画为言', primary: { traitId: 12, delta: 1.0 } },
      { text: '默而化之', gloss: '以默为言', primary: { traitId: 12, delta: -0.8 } },
      { text: '直陈其意', gloss: '以白为言', primary: { traitId: 12, delta: -1.2 } },
      { text: '托物以喻', gloss: '以喻为言', primary: { traitId: 12, delta: 0.4 } },
    ],
  },
  {
    id: 'el-047',
    format: 'aesthetic',
    prompt: '「言有尽而意无穷」',
    promptGloss: '对此语，汝所感最深者何？',
    options: [
      { text: '言有尽', gloss: '以言为限', primary: { traitId: 12, delta: -0.6 } },
      { text: '意无穷', gloss: '以意为远', primary: { traitId: 12, delta: 1.0 } },
      { text: '言意相生', gloss: '以相生为美', primary: { traitId: 12, delta: 0.6 } },
      { text: '不言而意', gloss: '以无言为上', primary: { traitId: 12, delta: -0.2 } },
      { text: '言之凿凿', gloss: '以言为实', primary: { traitId: 12, delta: -1.0 } },
      { text: '意在言先', gloss: '以意为先', primary: { traitId: 12, delta: 1.2 } },
    ],
  },
  {
    id: 'el-048',
    format: 'ranking',
    prompt: '四体，汝最擅',
    promptGloss: '「诗、词、文、赋」── 汝最擅何？',
    options: [
      { text: '诗', gloss: '以诗为言', primary: { traitId: 12, delta: 0.4 } },
      { text: '词', gloss: '以词为言', primary: { traitId: 12, delta: 1.0 } },
      { text: '文', gloss: '以文为言', primary: { traitId: 12, delta: 0.6 } },
      { text: '赋', gloss: '以赋为言', primary: { traitId: 12, delta: 1.2 } },
      { text: '皆不擅', gloss: '以不文为上', primary: { traitId: 12, delta: -1.2 } },
      { text: '皆兼擅', gloss: '以博为长', primary: { traitId: 12, delta: -0.6 } },
    ],
  },
];
