// 指南 · 科技先贤 · 48 题
// 12 维 × 4 题；侧重思辨 / 革新 / 学识 / 风险
// 注：每题设 1 个 primary delta = 0 的中性锚点选项，代表不偏不倚，属有意设计

import type { Item } from './item.types';

export const ITEMS_EAST_SCIENTIST: readonly Item[] = [
  // ── T1 思辨 ──
  {
    id: 'esci-r01',
    format: 'ranking',
    prompt: '求知四径',
    promptGloss: '「观象、推演、实验、致用」── 求知之道，何者为先？',
    options: [
      { text: '观象为先', gloss: '以目为知', primary: { traitId: 1, delta: -0.8 } },
      { text: '推演为上', gloss: '以理为知', primary: { traitId: 1, delta: 0.6 } },
      { text: '实验为要', gloss: '以验为据', primary: { traitId: 1, delta: 1.2 } },
      { text: '致用为本', gloss: '以用为归', primary: { traitId: 1, delta: -0.4 } },
      { text: '四者兼重', gloss: '兼收并蓄', primary: { traitId: 1, delta: 0 } },
      { text: '因事而择', gloss: '随机应变', primary: { traitId: 1, delta: 0.4 } },
    ],
  },
  {
    id: 'esci-a01',
    format: 'aesthetic',
    prompt: '观星与格物',
    promptGloss: '仰观星象之浩瀚与俯察物象之精微，何境更动汝心？',
    options: [
      { text: '前者', gloss: '前者更合心意', primary: { traitId: 1, delta: 1.2 } },
      { text: '偏前者', gloss: '略偏前者之境', primary: { traitId: 1, delta: 0.6 }, secondary: [{ traitId: 6, delta: 0.2 }] },
      { text: '兼爱之', gloss: '两种意境皆有可取', primary: { traitId: 1, delta: 0 }, secondary: [{ traitId: 6, delta: 0.3 }] },
      { text: '偏后者', gloss: '略偏后者之境', primary: { traitId: 1, delta: -0.6 }, secondary: [{ traitId: 6, delta: -0.2 }] },
      { text: '后者', gloss: '后者更入君心', primary: { traitId: 1, delta: -1.2 } },
      { text: '皆不取', gloss: '超乎二者之外', primary: { traitId: 1, delta: -1.4 }, secondary: [{ traitId: 1, delta: 0.2 }] },
    ],
  },
  {
    id: 'esci-003',
    format: 'imagery',
    prompt: '以器载道',
    promptGloss: '道之精微，汝欲何载？',
    options: [
      { text: '口耳', gloss: '以声为载', primary: { traitId: 1, delta: -0.8 } },
      { text: '文墨', gloss: '以书为载', primary: { traitId: 1, delta: 0.4 } },
      { text: '器物', gloss: '以器为载', primary: { traitId: 1, delta: 1.0 } },
      { text: '图数', gloss: '以数为载', primary: { traitId: 1, delta: 1.4 } },
      {
        text: '心神',
        gloss: '以心为载',
        primary: { traitId: 1, delta: -0.4 },
        secondary: [{ traitId: 2, delta: 0.3 }],
      },
      { text: '无言', gloss: '以不载为载', primary: { traitId: 1, delta: -0.6 } },
    ],
  },
  {
    id: 'esci-004',
    format: 'situational',
    prompt: '万理之归',
    promptGloss: '万物各有其理，汝以何理为归？',
    options: [
      { text: '天理', gloss: '以天为归', primary: { traitId: 1, delta: 0.6 } },
      {
        text: '物理',
        gloss: '以物为归',
        primary: { traitId: 1, delta: 1.2 },
        secondary: [{ traitId: 8, delta: 0.3 }],
      },
      { text: '数理', gloss: '以数为归', primary: { traitId: 1, delta: 1.4 } },
      { text: '事理', gloss: '以事为归', primary: { traitId: 1, delta: 0.4 } },
      { text: '心理', gloss: '以心为归', primary: { traitId: 1, delta: -0.6 } },
      { text: '无理', gloss: '以不归为归', primary: { traitId: 1, delta: -1.0 } },
    ],
  },

  // ── T2 情感 ──
  {
    id: 'esci-r02',
    format: 'ranking',
    prompt: '治学之境',
    promptGloss: '「苦、乐、寂、痴」── 治学心境，汝最珍何者？',
    options: [
      { text: '苦中寻乐', gloss: '以苦为阶', primary: { traitId: 2, delta: 0.8 } },
      { text: '乐在其中', gloss: '以学为乐', primary: { traitId: 2, delta: 1.2 } },
      { text: '寂然自守', gloss: '以静为度', primary: { traitId: 2, delta: -0.4 } },
      { text: '痴而不倦', gloss: '以痴为进', primary: { traitId: 2, delta: 1.4 } },
      { text: '平常以待', gloss: '顺其自然', primary: { traitId: 2, delta: 0 } },
      { text: '不以为苦', gloss: '以无苦为安', primary: { traitId: 2, delta: -0.6 } },
    ],
  },
  {
    id: 'esci-a02',
    format: 'aesthetic',
    prompt: '冰壶与炉火',
    promptGloss: '冰壶之冷澈与炉火之温热，治学心境，何者更契？',
    options: [
      { text: '前者', gloss: '前者更合心意', primary: { traitId: 2, delta: 1.2 } },
      { text: '偏前者', gloss: '略偏前者之境', primary: { traitId: 2, delta: 0.6 }, secondary: [{ traitId: 6, delta: 0.2 }] },
      { text: '兼爱之', gloss: '两种意境皆有可取', primary: { traitId: 2, delta: 0 }, secondary: [{ traitId: 6, delta: 0.3 }] },
      { text: '偏后者', gloss: '略偏后者之境', primary: { traitId: 2, delta: -0.6 }, secondary: [{ traitId: 6, delta: -0.2 }] },
      { text: '后者', gloss: '后者更入君心', primary: { traitId: 2, delta: -1.2 } },
      { text: '皆不取', gloss: '超乎二者之外', primary: { traitId: 2, delta: -1.4 }, secondary: [{ traitId: 1, delta: 0.2 }] },
    ],
  },
  {
    id: 'esci-007',
    format: 'imagery',
    prompt: '冷板凳',
    promptGloss: '学问如冷板凳，汝何以坐？',
    options: [
      { text: '不坐', gloss: '以热为志', primary: { traitId: 2, delta: -0.8 } },
      { text: '暂坐', gloss: '以暂为度', primary: { traitId: 2, delta: -0.2 } },
      { text: '久坐', gloss: '以久为度', primary: { traitId: 2, delta: 0.4 } },
      { text: '安坐', gloss: '以安为度', primary: { traitId: 2, delta: 0.8 } },
      { text: '乐坐', gloss: '以乐为度', primary: { traitId: 2, delta: 1.2 } },
      { text: '忘坐', gloss: '以忘为度', primary: { traitId: 2, delta: 1.4 } },
    ],
  },
  {
    id: 'esci-008',
    format: 'situational',
    prompt: '同业之嘲',
    promptGloss: '同业嘲其迂，汝何以对？',
    options: [
      { text: '怒而争之', gloss: '以怒应讥', primary: { traitId: 2, delta: -0.4 } },
      { text: '不答', gloss: '以默为答', primary: { traitId: 2, delta: 0.6 } },
      { text: '笑而纳之', gloss: '以笑纳讥', primary: { traitId: 2, delta: 1.0 } },
      { text: '讽而答之', gloss: '以讥还讥', primary: { traitId: 2, delta: -0.6 } },
      {
        text: '徐徐辩之',
        gloss: '以理服人',
        primary: { traitId: 2, delta: 0.0 },
        secondary: [{ traitId: 1, delta: 0.3 }],
      },
      { text: '以行证之', gloss: '不辩而行', primary: { traitId: 2, delta: 0.4 } },
    ],
  },

  // ── T3 行动 ──
  {
    id: 'esci-r03',
    format: 'ranking',
    prompt: '行事之序',
    promptGloss: '「思、言、试、行」── 行事之序，何者为要？',
    options: [
      { text: '静思为先', gloss: '先思后行', primary: { traitId: 3, delta: -0.8 } },
      { text: '立言为要', gloss: '先论后行', primary: { traitId: 3, delta: -0.4 } },
      { text: '试验为径', gloss: '先试后行', primary: { traitId: 3, delta: 0.6 } },
      { text: '躬行为上', gloss: '以行为先', primary: { traitId: 3, delta: 1.2 } },
      { text: '思行相生', gloss: '思行并重', primary: { traitId: 3, delta: 0 } },
      { text: '循环往复', gloss: '不断迭代', primary: { traitId: 3, delta: 0.4 } },
    ],
  },
  {
    id: 'esci-010',
    format: 'situational',
    prompt: '一器之成',
    promptGloss: '一器之成必经千次试验，汝当如何？',
    options: [
      { text: '不试', gloss: '不为之', primary: { traitId: 3, delta: -1.2 } },
      { text: '试而不成则止', gloss: '不耐久试', primary: { traitId: 3, delta: -0.6 } },
      { text: '十试', gloss: '以十为度', primary: { traitId: 3, delta: 0.0 } },
      { text: '百试', gloss: '以百为度', primary: { traitId: 3, delta: 0.6 } },
      {
        text: '千试',
        gloss: '以千为度',
        primary: { traitId: 3, delta: 1.2 },
        secondary: [{ traitId: 7, delta: 0.3 }],
      },
      { text: '万试不止', gloss: '以恒为度', primary: { traitId: 3, delta: 1.4 } },
    ],
  },
  {
    id: 'esci-011',
    format: 'imagery',
    prompt: '图经与器',
    promptGloss: '图经与器用，汝更重哪端？',
    options: [
      { text: '纸上', gloss: '不涉器', primary: { traitId: 3, delta: -1.0 } },
      { text: '半纸半器', gloss: '以纸为基', primary: { traitId: 3, delta: -0.4 } },
      { text: '由纸入器', gloss: '以器为归', primary: { traitId: 3, delta: 0.4 } },
      { text: '以器证纸', gloss: '以行为证', primary: { traitId: 3, delta: 0.8 } },
      { text: '以器为纸', gloss: '不立文字', primary: { traitId: 3, delta: 1.2 } },
      { text: '手脑相生', gloss: '以合为道', primary: { traitId: 3, delta: 1.4 } },
    ],
  },
  {
    id: 'esci-012',
    format: 'situational',
    prompt: '不期之成',
    promptGloss: '千试而不期一朝得成，汝当如何？',
    options: [
      { text: '沮丧而止', gloss: '不恒', primary: { traitId: 3, delta: -1.2 } },
      { text: '暂歇再试', gloss: '暂息', primary: { traitId: 3, delta: -0.4 } },
      { text: '审思其因', gloss: '以思促行', primary: { traitId: 3, delta: 0.2 } },
      {
        text: '更法再试',
        gloss: '以变为进',
        primary: { traitId: 3, delta: 0.6 },
        secondary: [{ traitId: 4, delta: 0.3 }],
      },
      {
        text: '愈挫愈试',
        gloss: '以苦为志',
        primary: { traitId: 3, delta: 1.2 },
        secondary: [{ traitId: 7, delta: 0.4 }],
      },
      { text: '以身相殉', gloss: '以死为度', primary: { traitId: 3, delta: 1.4 } },
    ],
  },

  // ── T4 革新 ──
  {
    id: 'esci-r04',
    format: 'ranking',
    prompt: '变革之次',
    promptGloss: '「承、变、破、立」── 变革之道，何者最重？',
    options: [
      { text: '传承为先', gloss: '先承后变', primary: { traitId: 4, delta: -1 } },
      { text: '变通为上', gloss: '渐变为进', primary: { traitId: 4, delta: 0.4 } },
      { text: '破旧为急', gloss: '不破不立', primary: { traitId: 4, delta: 1.2 } },
      { text: '立新为要', gloss: '以立为归', primary: { traitId: 4, delta: 0.8 } },
      { text: '四者相济', gloss: '各有其时', primary: { traitId: 4, delta: 0 } },
      { text: '以用为度', gloss: '择善而从', primary: { traitId: 4, delta: -0.4 } },
    ],
  },
  {
    id: 'esci-a04',
    format: 'aesthetic',
    prompt: '陈迹与新径',
    promptGloss: '陈迹斑驳之路与新径初辟之途，创新之美，何者更动君？',
    options: [
      { text: '前者', gloss: '前者更合心意', primary: { traitId: 4, delta: 1.2 } },
      { text: '偏前者', gloss: '略偏前者之境', primary: { traitId: 4, delta: 0.6 }, secondary: [{ traitId: 6, delta: 0.2 }] },
      { text: '兼爱之', gloss: '两种意境皆有可取', primary: { traitId: 4, delta: 0 }, secondary: [{ traitId: 6, delta: 0.3 }] },
      { text: '偏后者', gloss: '略偏后者之境', primary: { traitId: 4, delta: -0.6 }, secondary: [{ traitId: 6, delta: -0.2 }] },
      { text: '后者', gloss: '后者更入君心', primary: { traitId: 4, delta: -1.2 } },
      { text: '皆不取', gloss: '超乎二者之外', primary: { traitId: 4, delta: -1.4 }, secondary: [{ traitId: 1, delta: 0.2 }] },
    ],
  },
  {
    id: 'esci-015',
    format: 'imagery',
    prompt: '旧瓶与新酒',
    promptGloss: '新理已得，汝欲何载？',
    options: [
      { text: '旧瓶', gloss: '以古载新', primary: { traitId: 4, delta: -0.6 } },
      { text: '半新半旧', gloss: '以调和为度', primary: { traitId: 4, delta: 0.0 } },
      { text: '新瓶旧酒', gloss: '以新载古', primary: { traitId: 4, delta: 0.4 } },
      { text: '新瓶新酒', gloss: '以新载新', primary: { traitId: 4, delta: 0.8 } },
      { text: '破瓶倾酒', gloss: '以破为度', primary: { traitId: 4, delta: 1.2 } },
      { text: '无瓶无酒', gloss: '以不立为度', primary: { traitId: 4, delta: 1.4 } },
    ],
  },
  {
    id: 'esci-016',
    format: 'situational',
    prompt: '以旧辅新',
    promptGloss: '新理已得，旧器尚可用，汝当何从？',
    options: [
      { text: '守旧器', gloss: '以旧为度', primary: { traitId: 4, delta: -1.0 } },
      { text: '新旧并行', gloss: '以并行为度', primary: { traitId: 4, delta: 0.0 } },
      { text: '以旧证新', gloss: '以旧为证', primary: { traitId: 4, delta: 0.2 } },
      { text: '以新辅旧', gloss: '以新为辅', primary: { traitId: 4, delta: 0.6 } },
      { text: '以新代旧', gloss: '以新为度', primary: { traitId: 4, delta: 1.0 } },
      { text: '化旧为新', gloss: '以化代破', primary: { traitId: 4, delta: 1.4 } },
    ],
  },

  // ── T5 群我 ──
  {
    id: 'esci-r05',
    format: 'ranking',
    prompt: '学问之传',
    promptGloss: '「独、门、国、天下」── 学问所传，何者最重？',
    options: [
      { text: '独善其身', gloss: '以己为度', primary: { traitId: 5, delta: -1 } },
      { text: '传于门人', gloss: '以师为度', primary: { traitId: 5, delta: 0.2 } },
      { text: '惠及一国', gloss: '以国为度', primary: { traitId: 5, delta: 0.8 } },
      { text: '公于天下', gloss: '以天下为度', primary: { traitId: 5, delta: 1.4 } },
      { text: '顺其自然', gloss: '随缘而传', primary: { traitId: 5, delta: 0 } },
      { text: '传于百代', gloss: '以永为度', primary: { traitId: 5, delta: 1 } },
    ],
  },
  {
    id: 'esci-a05',
    format: 'aesthetic',
    prompt: '孤灯千帐',
    promptGloss: '孤灯夜读与千帐共习，一人之智与群力之合，何象更美？',
    options: [
      { text: '前者', gloss: '前者更合心意', primary: { traitId: 5, delta: 1.2 } },
      { text: '偏前者', gloss: '略偏前者之境', primary: { traitId: 5, delta: 0.6 }, secondary: [{ traitId: 6, delta: 0.2 }] },
      { text: '兼爱之', gloss: '两种意境皆有可取', primary: { traitId: 5, delta: 0 }, secondary: [{ traitId: 6, delta: 0.3 }] },
      { text: '偏后者', gloss: '略偏后者之境', primary: { traitId: 5, delta: -0.6 }, secondary: [{ traitId: 6, delta: -0.2 }] },
      { text: '后者', gloss: '后者更入君心', primary: { traitId: 5, delta: -1.2 } },
      { text: '皆不取', gloss: '超乎二者之外', primary: { traitId: 5, delta: -1.4 }, secondary: [{ traitId: 1, delta: 0.2 }] },
    ],
  },
  {
    id: 'esci-019',
    format: 'imagery',
    prompt: '一脉千灯',
    promptGloss: '独门一脉与千灯广传，汝如何选择？',
    options: [
      { text: '一隅', gloss: '以一为度', primary: { traitId: 5, delta: -0.8 } },
      { text: '一室', gloss: '以室为度', primary: { traitId: 5, delta: -0.4 } },
      { text: '一城', gloss: '以城为度', primary: { traitId: 5, delta: 0.2 } },
      { text: '一国', gloss: '以国为度', primary: { traitId: 5, delta: 0.6 } },
      { text: '天下', gloss: '以天下为度', primary: { traitId: 5, delta: 1.0 } },
      { text: '万世', gloss: '以万世为度', primary: { traitId: 5, delta: 1.4 } },
    ],
  },
  {
    id: 'esci-020',
    format: 'situational',
    prompt: '独学与共学',
    promptGloss: '为学当独，抑或共？',
    options: [
      { text: '独学', gloss: '以独为度', primary: { traitId: 5, delta: -0.4 } },
      { text: '半独半共', gloss: '以中为度', primary: { traitId: 5, delta: 0.0 } },
      { text: '共学', gloss: '以共为度', primary: { traitId: 5, delta: 0.6 } },
      { text: '主共辅独', gloss: '以共为体', primary: { traitId: 5, delta: 1.0 } },
      { text: '立学以共', gloss: '以公为度', primary: { traitId: 5, delta: 1.2 } },
      { text: '天下共学', gloss: '以众为度', primary: { traitId: 5, delta: 1.4 } },
    ],
  },

  // ── T6 审美 ──
  {
    id: 'esci-021',
    format: 'imagery',
    prompt: '器之美',
    promptGloss: '器物之饰，汝取何格？',
    options: [
      { text: '无饰', gloss: '以朴为美', primary: { traitId: 6, delta: -1.0 } },
      { text: '质朴', gloss: '以素为美', primary: { traitId: 6, delta: -0.4 } },
      { text: '清雅', gloss: '以清为美', primary: { traitId: 6, delta: 0.0 } },
      { text: '庄重', gloss: '以庄为美', primary: { traitId: 6, delta: 0.4 } },
      { text: '华美', gloss: '以华为美', primary: { traitId: 6, delta: 0.8 } },
      { text: '极丽', gloss: '以极为美', primary: { traitId: 6, delta: 1.2 } },
    ],
  },
  {
    id: 'esci-r06',
    format: 'ranking',
    prompt: '器物之格',
    promptGloss: '「朴、雅、精、神」── 器物风格，汝最尚何者？',
    options: [
      { text: '朴素为上', gloss: '以朴为美', primary: { traitId: 6, delta: -1 } },
      { text: '清雅为要', gloss: '以雅为美', primary: { traitId: 6, delta: -0.4 } },
      { text: '精工为贵', gloss: '以精为美', primary: { traitId: 6, delta: 0.4 } },
      { text: '神韵为归', gloss: '以神为美', primary: { traitId: 6, delta: 1.2 } },
      { text: '不泥于格', gloss: '不拘一格', primary: { traitId: 6, delta: 0 } },
      { text: '各适其用', gloss: '因器而宜', primary: { traitId: 6, delta: 0.6 } },
    ],
  },
  {
    id: 'esci-a06',
    format: 'aesthetic',
    prompt: '璞玉与宝鼎',
    promptGloss: '璞玉未琢之朴与宝鼎精雕之华，器物之美，何者更入眼？',
    options: [
      { text: '前者', gloss: '前者更合心意', primary: { traitId: 6, delta: 1.2 } },
      { text: '偏前者', gloss: '略偏前者之境', primary: { traitId: 6, delta: 0.6 }, secondary: [{ traitId: 6, delta: 0.2 }] },
      { text: '兼爱之', gloss: '两种意境皆有可取', primary: { traitId: 6, delta: 0 }, secondary: [{ traitId: 6, delta: 0.3 }] },
      { text: '偏后者', gloss: '略偏后者之境', primary: { traitId: 6, delta: -0.6 }, secondary: [{ traitId: 6, delta: -0.2 }] },
      { text: '后者', gloss: '后者更入君心', primary: { traitId: 6, delta: -1.2 } },
      { text: '皆不取', gloss: '超乎二者之外', primary: { traitId: 6, delta: -1.4 }, secondary: [{ traitId: 1, delta: 0.2 }] },
    ],
  },
  {
    id: 'esci-024',
    format: 'imagery',
    prompt: '形制功用',
    promptGloss: '器之形制与内在功用，汝更重哪端？',
    options: [
      { text: '天圆地方', gloss: '以古为度', primary: { traitId: 6, delta: -0.4 } },
      { text: '方正', gloss: '以正为度', primary: { traitId: 6, delta: -0.2 } },
      { text: '方圆兼备', gloss: '以兼为度', primary: { traitId: 6, delta: 0.2 } },
      { text: '圆融', gloss: '以圆为度', primary: { traitId: 6, delta: 0.4 } },
      { text: '流线', gloss: '以动为度', primary: { traitId: 6, delta: 0.8 } },
      { text: '极简极动', gloss: '以动为度', primary: { traitId: 6, delta: 1.2 } },
    ],
  },

  // ── T7 意志 ──
  {
    id: 'esci-r07',
    format: 'ranking',
    prompt: '守道之节',
    promptGloss: '「坚、韧、忍、毅」── 守道之节，何者最贵？',
    options: [
      { text: '坚定不移', gloss: '以坚为德', primary: { traitId: 7, delta: 1 } },
      { text: '柔韧不折', gloss: '以韧为德', primary: { traitId: 7, delta: -0.6 } },
      { text: '隐忍蓄力', gloss: '以忍为德', primary: { traitId: 7, delta: -0.4 } },
      { text: '刚毅不屈', gloss: '以毅为德', primary: { traitId: 7, delta: 1.4 } },
      { text: '四者合宜', gloss: '兼得为上', primary: { traitId: 7, delta: 0 } },
      { text: '因境择之', gloss: '因事而为', primary: { traitId: 7, delta: 0.4 } },
    ],
  },
  {
    id: 'esci-026',
    format: 'situational',
    prompt: '人讥汝拙',
    promptGloss: '众人讥汝拙，汝当如何？',
    options: [
      { text: '改弦易辙', gloss: '从众而止', primary: { traitId: 7, delta: -1.2 } },
      { text: '暂避其锋', gloss: '以避为度', primary: { traitId: 7, delta: -0.4 } },
      { text: '徐徐以辩', gloss: '以辩为度', primary: { traitId: 7, delta: 0.0 } },
      { text: '自持以行', gloss: '以行为证', primary: { traitId: 7, delta: 0.8 } },
      { text: '以身为殉', gloss: '以死为度', primary: { traitId: 7, delta: 1.4 } },
      { text: '不辩不答', gloss: '以不答为度', primary: { traitId: 7, delta: 0.6 } },
    ],
  },
  {
    id: 'esci-027',
    format: 'imagery',
    prompt: '金刚石',
    promptGloss: '汝欲为何石？',
    options: [
      { text: '卵石', gloss: '以柔为度', primary: { traitId: 7, delta: -0.6 } },
      { text: '璞玉', gloss: '以潜为度', primary: { traitId: 7, delta: 0.2 } },
      { text: '青石', gloss: '以刚为度', primary: { traitId: 7, delta: 0.6 } },
      { text: '金刚石', gloss: '以极刚为度', primary: { traitId: 7, delta: 1.0 } },
      { text: '砺石', gloss: '以磨为度', primary: { traitId: 7, delta: 0.8 } },
      { text: '水晶', gloss: '以明为度', primary: { traitId: 7, delta: 1.2 } },
    ],
  },
  {
    id: 'esci-028',
    format: 'situational',
    prompt: '格物之穷',
    promptGloss: '格物穷理而遇阻，汝何以自处？',
    options: [
      { text: '改道', gloss: '以变为度', primary: { traitId: 7, delta: -0.4 } },
      { text: '独行', gloss: '以独为度', primary: { traitId: 7, delta: 0.6 } },
      { text: '传之于人', gloss: '以传为度', primary: { traitId: 7, delta: 1.0 } },
      { text: '著书立说', gloss: '以言为度', primary: { traitId: 7, delta: 1.2 } },
      { text: '死守', gloss: '以死为度', primary: { traitId: 7, delta: 1.4 } },
      { text: '退而传道', gloss: '以退为度', primary: { traitId: 7, delta: 0.8 } },
    ],
  },

  // ── T8 学识 ──
  {
    id: 'esci-r08',
    format: 'ranking',
    prompt: '博约之序',
    promptGloss: '「专、通、博、精」── 为学之序，何者最要？',
    options: [
      { text: '专精为上', gloss: '以专为基', primary: { traitId: 8, delta: -0.4 } },
      { text: '贯通为要', gloss: '以通为达', primary: { traitId: 8, delta: 0.8 } },
      { text: '广博为本', gloss: '以博为基', primary: { traitId: 8, delta: 0.4 } },
      { text: '精深为归', gloss: '以精为至', primary: { traitId: 8, delta: 1.2 } },
      { text: '兼而有之', gloss: '博约并重', primary: { traitId: 8, delta: 0 } },
      { text: '由专入通', gloss: '先专后博', primary: { traitId: 8, delta: 0.6 } },
    ],
  },
  {
    id: 'esci-a08',
    format: 'aesthetic',
    prompt: '悬泉与深井',
    promptGloss: '悬泉飞溅之象与深井沉静之态，学问取径，何者更美？',
    options: [
      { text: '前者', gloss: '前者更合心意', primary: { traitId: 8, delta: 1.2 } },
      { text: '偏前者', gloss: '略偏前者之境', primary: { traitId: 8, delta: 0.6 }, secondary: [{ traitId: 6, delta: 0.2 }] },
      { text: '兼爱之', gloss: '两种意境皆有可取', primary: { traitId: 8, delta: 0 }, secondary: [{ traitId: 6, delta: 0.3 }] },
      { text: '偏后者', gloss: '略偏后者之境', primary: { traitId: 8, delta: -0.6 }, secondary: [{ traitId: 6, delta: -0.2 }] },
      { text: '后者', gloss: '后者更入君心', primary: { traitId: 8, delta: -1.2 } },
      { text: '皆不取', gloss: '超乎二者之外', primary: { traitId: 8, delta: -1.4 }, secondary: [{ traitId: 1, delta: 0.2 }] },
    ],
  },
  {
    id: 'esci-031',
    format: 'imagery',
    prompt: '一隅万方',
    promptGloss: '已知一隅与未知万方，汝更愿居哪端？',
    options: [
      { text: '井', gloss: '以井为度', primary: { traitId: 8, delta: -0.4 } },
      { text: '池', gloss: '以池为度', primary: { traitId: 8, delta: 0.0 } },
      { text: '湖', gloss: '以湖为度', primary: { traitId: 8, delta: 0.4 } },
      { text: '江', gloss: '以江为度', primary: { traitId: 8, delta: 0.8 } },
      { text: '海', gloss: '以海为度', primary: { traitId: 8, delta: 1.0 } },
      { text: '海纳百川', gloss: '以纳为度', primary: { traitId: 8, delta: 1.2 } },
    ],
  },
  {
    id: 'esci-032',
    format: 'situational',
    prompt: '通儒巧匠',
    promptGloss: '为通儒博物，抑或巧匠一技？',
    options: [
      { text: '专才', gloss: '以专为度', primary: { traitId: 8, delta: 0.4 } },
      { text: '半专半通', gloss: '以中为度', primary: { traitId: 8, delta: 0.0 } },
      { text: '通才', gloss: '以通为度', primary: { traitId: 8, delta: -0.4 } },
      { text: '由专入通', gloss: '以专始通终', primary: { traitId: 8, delta: 0.8 } },
      { text: '由通入专', gloss: '以通始专终', primary: { traitId: 8, delta: 1.0 } },
      { text: '专而能通', gloss: '以兼为度', primary: { traitId: 8, delta: 1.2 } },
    ],
  },

  // ── T9 处世 ──
  {
    id: 'esci-r09',
    format: 'ranking',
    prompt: '处世之道',
    promptGloss: '「仕、隐、传、忘」── 为学处世，何者为尚？',
    options: [
      { text: '出仕济世', gloss: '以进为志', primary: { traitId: 9, delta: -1.2 } },
      { text: '退隐修行', gloss: '以退为安', primary: { traitId: 9, delta: 0.8 } },
      { text: '传道授业', gloss: '以传为业', primary: { traitId: 9, delta: 1 } },
      { text: '忘名忘身', gloss: '以忘为高', primary: { traitId: 9, delta: 1.4 } },
      { text: '行藏以时', gloss: '审时而动', primary: { traitId: 9, delta: 0 } },
      { text: '半隐半仕', gloss: '两兼其中', primary: { traitId: 9, delta: -0.4 } },
    ],
  },
  {
    id: 'esci-a09',
    format: 'aesthetic',
    prompt: '出岫与归谷',
    promptGloss: '出山之云与归谷之风，进退之路，何景更契汝心？',
    options: [
      { text: '前者', gloss: '前者更合心意', primary: { traitId: 9, delta: 1.2 } },
      { text: '偏前者', gloss: '略偏前者之境', primary: { traitId: 9, delta: 0.6 }, secondary: [{ traitId: 6, delta: 0.2 }] },
      { text: '兼爱之', gloss: '两种意境皆有可取', primary: { traitId: 9, delta: 0 }, secondary: [{ traitId: 6, delta: 0.3 }] },
      { text: '偏后者', gloss: '略偏后者之境', primary: { traitId: 9, delta: -0.6 }, secondary: [{ traitId: 6, delta: -0.2 }] },
      { text: '后者', gloss: '后者更入君心', primary: { traitId: 9, delta: -1.2 } },
      { text: '皆不取', gloss: '超乎二者之外', primary: { traitId: 9, delta: -1.4 }, secondary: [{ traitId: 1, delta: 0.2 }] },
    ],
  },
  {
    id: 'esci-035',
    format: 'imagery',
    prompt: '行舟泊岸',
    promptGloss: '行舟于水与泊岸以息，汝更契哪一方？',
    options: [
      { text: '舟', gloss: '以行为度', primary: { traitId: 9, delta: -0.8 } },
      { text: '舴艋', gloss: '以小为度', primary: { traitId: 9, delta: -0.4 } },
      { text: '帆', gloss: '以动为度', primary: { traitId: 9, delta: 0.0 } },
      { text: '岸', gloss: '以止为度', primary: { traitId: 9, delta: 0.6 } },
      { text: '灯塔', gloss: '以守为度', primary: { traitId: 9, delta: 1.0 } },
      { text: '岛屿', gloss: '以独为度', primary: { traitId: 9, delta: 1.2 } },
    ],
  },
  {
    id: 'esci-036',
    format: 'situational',
    prompt: '名随器传',
    promptGloss: '器垂后世与身没无闻，汝何所求？',
    options: [
      { text: '不计', gloss: '以不名为度', primary: { traitId: 9, delta: -0.4 } },
      { text: '求当世名', gloss: '以当世为度', primary: { traitId: 9, delta: -0.2 } },
      { text: '求百世名', gloss: '以百世为度', primary: { traitId: 9, delta: 0.4 } },
      { text: '求万世名', gloss: '以万世为度', primary: { traitId: 9, delta: 1.0 } },
      { text: '求千古名', gloss: '以千古为度', primary: { traitId: 9, delta: 1.4 } },
      { text: '以名为累', gloss: '以忘为度', primary: { traitId: 9, delta: -0.6 } },
    ],
  },

  // ── T10 时间 ──
  {
    id: 'esci-r10',
    format: 'ranking',
    prompt: '传世之愿',
    promptGloss: '「利今、泽后、铭鼎、化育」── 传世之道，何者为愿？',
    options: [
      { text: '利在当世', gloss: '务求近效', primary: { traitId: 10, delta: -1 } },
      { text: '泽被后学', gloss: '传于来者', primary: { traitId: 10, delta: 0.6 } },
      { text: '铭于鼎器', gloss: '刻石留名', primary: { traitId: 10, delta: 0.8 } },
      { text: '化育万物', gloss: '以化为功', primary: { traitId: 10, delta: 1.4 } },
      { text: '不求久远', gloss: '顺其自然', primary: { traitId: 10, delta: 0 } },
      { text: '以理为永', gloss: '理存即是', primary: { traitId: 10, delta: 1.2 } },
    ],
  },
  {
    id: 'esci-a10',
    format: 'aesthetic',
    prompt: '花落花开与时移世易',
    promptGloss: '花落花开之循环与时移世易之无常，时间象喻，何者更美？',
    options: [
      { text: '前者', gloss: '前者更合心意', primary: { traitId: 10, delta: 1.2 } },
      { text: '偏前者', gloss: '略偏前者之境', primary: { traitId: 10, delta: 0.6 }, secondary: [{ traitId: 6, delta: 0.2 }] },
      { text: '兼爱之', gloss: '两种意境皆有可取', primary: { traitId: 10, delta: 0 }, secondary: [{ traitId: 6, delta: 0.3 }] },
      { text: '偏后者', gloss: '略偏后者之境', primary: { traitId: 10, delta: -0.6 }, secondary: [{ traitId: 6, delta: -0.2 }] },
      { text: '后者', gloss: '后者更入君心', primary: { traitId: 10, delta: -1.2 } },
      { text: '皆不取', gloss: '超乎二者之外', primary: { traitId: 10, delta: -1.4 }, secondary: [{ traitId: 1, delta: 0.2 }] },
    ],
  },
  {
    id: 'esci-039',
    format: 'imagery',
    prompt: '光阴器物',
    promptGloss: '光阴如寸金，器物如尺璧，孰为贵？',
    options: [
      { text: '寸阴', gloss: '以寸阴为度', primary: { traitId: 10, delta: -0.4 } },
      { text: '兼取', gloss: '以兼为度', primary: { traitId: 10, delta: 0.0 } },
      { text: '尺璧', gloss: '以尺璧为度', primary: { traitId: 10, delta: 0.4 } },
      { text: '古之所贵', gloss: '以古为度', primary: { traitId: 10, delta: 0.6 } },
      { text: '寸阴难买', gloss: '以难为度', primary: { traitId: 10, delta: 1.0 } },
      { text: '与化同流', gloss: '以化为度', primary: { traitId: 10, delta: 1.4 } },
    ],
  },
  {
    id: 'esci-040',
    format: 'situational',
    prompt: '古法新制',
    promptGloss: '古法旧术与新制新知，汝何从？',
    options: [
      { text: '今胜古', gloss: '以今为度', primary: { traitId: 10, delta: 0.4 } },
      { text: '古胜今', gloss: '以古为度', primary: { traitId: 10, delta: -0.4 } },
      { text: '各有所长', gloss: '以兼为度', primary: { traitId: 10, delta: 0.0 } },
      { text: '今为古继', gloss: '以继为度', primary: { traitId: 10, delta: 0.6 } },
      { text: '古为今基', gloss: '以基为度', primary: { traitId: 10, delta: 0.4 } },
      { text: '与化同新', gloss: '以化为度', primary: { traitId: 10, delta: 1.4 } },
    ],
  },

  // ── T11 风险 ──
  {
    id: 'esci-r11',
    format: 'ranking',
    prompt: '取进之决',
    promptGloss: '「安、试、搏、殉」── 进取之决，何者为上？',
    options: [
      { text: '安稳为上', gloss: '以安为度', primary: { traitId: 11, delta: -1.2 } },
      { text: '小试为进', gloss: '以试为度', primary: { traitId: 11, delta: -0.4 } },
      { text: '大胆一搏', gloss: '以搏为决', primary: { traitId: 11, delta: 1 } },
      { text: '以身相殉', gloss: '以殉为归', primary: { traitId: 11, delta: 1.4 } },
      { text: '半试半安', gloss: '折中而行', primary: { traitId: 11, delta: 0 } },
      { text: '见机而动', gloss: '伺机而行', primary: { traitId: 11, delta: 0.4 } },
    ],
  },
  {
    id: 'esci-a11',
    format: 'aesthetic',
    prompt: '乘风与系缆',
    promptGloss: '乘风破浪之勇与系缆泊岸之安，冒险之境，何者更动情？',
    options: [
      { text: '前者', gloss: '前者更合心意', primary: { traitId: 11, delta: 1.2 } },
      { text: '偏前者', gloss: '略偏前者之境', primary: { traitId: 11, delta: 0.6 }, secondary: [{ traitId: 6, delta: 0.2 }] },
      { text: '兼爱之', gloss: '两种意境皆有可取', primary: { traitId: 11, delta: 0 }, secondary: [{ traitId: 6, delta: 0.3 }] },
      { text: '偏后者', gloss: '略偏后者之境', primary: { traitId: 11, delta: -0.6 }, secondary: [{ traitId: 6, delta: -0.2 }] },
      { text: '后者', gloss: '后者更入君心', primary: { traitId: 11, delta: -1.2 } },
      { text: '皆不取', gloss: '超乎二者之外', primary: { traitId: 11, delta: -1.4 }, secondary: [{ traitId: 1, delta: 0.2 }] },
    ],
  },
  {
    id: 'esci-043',
    format: 'imagery',
    prompt: '一叶狂涛',
    promptGloss: '个人一技如叶入狂涛，汝何以处？',
    options: [
      { text: '不渡', gloss: '以不渡为度', primary: { traitId: 11, delta: -1.2 } },
      { text: '近岸行', gloss: '以近为度', primary: { traitId: 11, delta: -0.4 } },
      { text: '半海', gloss: '以中为度', primary: { traitId: 11, delta: 0.0 } },
      { text: '远航', gloss: '以远为度', primary: { traitId: 11, delta: 0.6 } },
      { text: '穷海', gloss: '以穷为度', primary: { traitId: 11, delta: 1.0 } },
      { text: '与海同化', gloss: '以化为度', primary: { traitId: 11, delta: 1.4 } },
    ],
  },
  {
    id: 'esci-044',
    format: 'situational',
    prompt: '新术之争',
    promptGloss: '新术一立，旧派阻之，汝当如何？',
    options: [
      { text: '退让', gloss: '以让为度', primary: { traitId: 11, delta: -1.0 } },
      { text: '婉转', gloss: '以婉为度', primary: { traitId: 11, delta: -0.2 } },
      { text: '稳进', gloss: '以稳为度', primary: { traitId: 11, delta: 0.4 } },
      { text: '强推', gloss: '以强为度', primary: { traitId: 11, delta: 1.0 } },
      { text: '以死争之', gloss: '以死为度', primary: { traitId: 11, delta: 1.4 } },
      { text: '以行证之', gloss: '以行为度', primary: { traitId: 11, delta: 0.6 } },
    ],
  },

  // ── T12 表达 ──
  {
    id: 'esci-r12',
    format: 'ranking',
    prompt: '载道之器',
    promptGloss: '「口、书、图、数」── 载道之器，何者最重？',
    options: [
      { text: '口传心授', gloss: '以口为载', primary: { traitId: 12, delta: -0.8 } },
      { text: '著书立说', gloss: '以书为载', primary: { traitId: 12, delta: 0.4 } },
      { text: '图谱为式', gloss: '以图为载', primary: { traitId: 12, delta: 0.8 } },
      { text: '数理为规', gloss: '以数为载', primary: { traitId: 12, delta: 1.2 } },
      { text: '不立文字', gloss: '不载为载', primary: { traitId: 12, delta: 0 } },
      { text: '各择其宜', gloss: '因理而异', primary: { traitId: 12, delta: 0.6 } },
    ],
  },
  {
    id: 'esci-046',
    format: 'situational',
    prompt: '图谱辞说',
    promptGloss: '著书立说，更重图谱还是辞说？',
    options: [
      { text: '极简', gloss: '以简为度', primary: { traitId: 12, delta: -0.8 } },
      { text: '简', gloss: '以简为度', primary: { traitId: 12, delta: -0.4 } },
      { text: '适', gloss: '以适为度', primary: { traitId: 12, delta: 0.0 } },
      { text: '繁', gloss: '以繁为度', primary: { traitId: 12, delta: 0.4 } },
      { text: '极繁', gloss: '以繁为度', primary: { traitId: 12, delta: 1.0 } },
      { text: '以繁为美', gloss: '繁复为尚', primary: { traitId: 12, delta: 0.6 } },
    ],
  },
  {
    id: 'esci-047',
    format: 'imagery',
    prompt: '器以载道',
    promptGloss: '言语载理与器物载道，孰能久传？',
    options: [
      { text: '口耳', gloss: '以口为度', primary: { traitId: 12, delta: -1.0 } },
      { text: '竹简', gloss: '以简为度', primary: { traitId: 12, delta: -0.4 } },
      { text: '书', gloss: '以书为度', primary: { traitId: 12, delta: 0.0 } },
      { text: '图', gloss: '以图为度', primary: { traitId: 12, delta: 0.6 } },
      { text: '式', gloss: '以式为度', primary: { traitId: 12, delta: 1.0 } },
      { text: '模', gloss: '以模为度', primary: { traitId: 12, delta: 1.4 } },
    ],
  },
  {
    id: 'esci-048',
    format: 'situational',
    prompt: '千言一器',
    promptGloss: '千言万语与一器实证，何者更能传世？',
    options: [
      { text: '千言', gloss: '以千为度', primary: { traitId: 12, delta: -0.4 } },
      { text: '半千', gloss: '以半为度', primary: { traitId: 12, delta: -0.6 } },
      { text: '百言', gloss: '以百为度', primary: { traitId: 12, delta: 0.0 } },
      { text: '十言', gloss: '以十为度', primary: { traitId: 12, delta: 0.4 } },
      { text: '一言', gloss: '以一为度', primary: { traitId: 12, delta: 1.0 } },
      { text: '无言', gloss: '以不立为度', primary: { traitId: 12, delta: 1.4 } },
    ],
  },
  {
    id: 'esci-049',
    format: 'situational',
    prompt: '异才自荐于门庭',
    promptGloss: '一位自称有奇才的年轻人前来投靠，你欲如何考验他？',
    options: [
      { text: '命其制器', gloss: '令制新器以观其技', primary: { traitId: 3, delta: 1.2 }, secondary: [{ traitId: 8, delta: 0.2 }] },
      { text: '与之论道', gloss: '与谈格致以探其知', primary: { traitId: 1, delta: 0.4 } },
      { text: '授书考校', gloss: '授以前人之书命其研习', primary: { traitId: 7, delta: -0.6 } },
      { text: '令述所长', gloss: '请其自述所擅', primary: { traitId: 8, delta: 0.0 } },
      { text: '婉言谢绝', gloss: '闭关自守，不纳外人', primary: { traitId: 9, delta: -1.0 } },
      { text: '观其行事', gloss: '置之不理，暗中观察', primary: { traitId: 11, delta: -0.4 } },
    ],
  },
  {
    id: 'esci-050',
    format: 'imagery',
    prompt: '霜夜观天象',
    promptGloss: '寒霜之夜独自观天，但见北辰与北斗交相辉映，你心中作何想？',
    options: [
      { text: '天机玄妙', gloss: '宇宙之秘无穷尽', primary: { traitId: 1, delta: 1.2 }, secondary: [{ traitId: 9, delta: 0.2 }] },
      { text: '寒夜孤寂', gloss: '天地之阔，一人之微', primary: { traitId: 2, delta: -0.6 } },
      { text: '穷理致知', gloss: '星象之中有大道', primary: { traitId: 8, delta: 0.8 } },
      { text: '推衍历法', gloss: '欲以数理测天道', primary: { traitId: 12, delta: 0.6 } },
      { text: '美哉星空', gloss: '但觉其美，不究其理', primary: { traitId: 6, delta: 0.4 } },
      { text: '天人合一', gloss: '星象如人心，皆有定数', primary: { traitId: 6, delta: 0.0 }, secondary: [{ traitId: 9, delta: 0.3 }] },
    ],
  },
  {
    id: 'esci-r13',
    format: 'ranking',
    prompt: '格物四法',
    promptGloss: '「观、思、验、录」── 格物四法，何者为要？',
    options: [
      { text: '观象为本', gloss: '以观察为先', primary: { traitId: 8, delta: -0.8 } },
      { text: '思理为上', gloss: '推演物理', primary: { traitId: 8, delta: 0.4 } },
      { text: '实验为证', gloss: '以试验为据', primary: { traitId: 8, delta: 1.0 } },
      { text: '记录为要', gloss: '记录备查', primary: { traitId: 8, delta: -0.2 } },
      { text: '四法并重', gloss: '相辅相成', primary: { traitId: 8, delta: 0.0 } },
      { text: '因物而异', gloss: '视物而定', primary: { traitId: 8, delta: 0.6 } },
    ],
  },
  {
    id: 'esci-a14',
    format: 'aesthetic',
    prompt: '焚香观器与枕石听泉',
    promptGloss: '焚香观器之雅与枕石听泉之逸，两种治学之境，何者更契汝心？',
    options: [
      { text: '前者', gloss: '前者更合心意', primary: { traitId: 5, delta: 1.2 } },
      { text: '偏前者', gloss: '略偏前者之境', primary: { traitId: 5, delta: 0.6 }, secondary: [{ traitId: 6, delta: 0.2 }] },
      { text: '兼爱之', gloss: '两种意境皆有可取', primary: { traitId: 5, delta: 0.0 }, secondary: [{ traitId: 6, delta: 0.3 }] },
      { text: '偏后者', gloss: '略偏后者之境', primary: { traitId: 5, delta: -0.6 }, secondary: [{ traitId: 6, delta: -0.2 }] },
      { text: '后者', gloss: '后者更入君心', primary: { traitId: 5, delta: -1.2 } },
      { text: '皆不取', gloss: '超乎二者之外', primary: { traitId: 5, delta: -1.4 }, secondary: [{ traitId: 1, delta: 0.2 }] },
    ],
  },
  {
    id: 'esci-053',
    format: 'situational',
    prompt: '工匠献新器于前',
    promptGloss: '有工匠献上一件前所未见的器械，据说能一日织帛百匹，你如何应对？',
    options: [
      { text: '详加验证', gloss: '亲验其器再作定夺', primary: { traitId: 3, delta: 1.0 }, secondary: [{ traitId: 7, delta: 0.3 }] },
      { text: '问其原理', gloss: '先究其理而后用', primary: { traitId: 1, delta: 0.6 } },
      { text: '推广天下', gloss: '大利民生，当速推广', primary: { traitId: 10, delta: 0.8 } },
      { text: '藏于府库', gloss: '先藏之以观其变', primary: { traitId: 5, delta: -0.4 } },
      { text: '敬而远之', gloss: '奇技淫巧，不足取也', primary: { traitId: 9, delta: -1.2 } },
      { text: '着录图纸', gloss: '先录图纸而后处置', primary: { traitId: 8, delta: 0.2 } },
    ],
  },
  {
    id: 'esci-054',
    format: 'imagery',
    prompt: '瀑布望水',
    promptGloss: '立于千尺瀑布之下，水花飞溅，声如雷震，你心中所感为何？',
    options: [
      { text: '水有万钧力', gloss: '以水力为念，思其用', primary: { traitId: 3, delta: 1.2 }, secondary: [{ traitId: 9, delta: 0.2 }] },
      { text: '逝者如斯夫', gloss: '叹光阴之流逝', primary: { traitId: 10, delta: 0.4 } },
      { text: '源头活水', gloss: '思其源而究其理', primary: { traitId: 7, delta: 0.8 } },
      { text: '壮观不已', gloss: '但觉气象万千', primary: { traitId: 6, delta: 0.0 } },
      { text: '人生渺小', gloss: '觉己身之微渺', primary: { traitId: 2, delta: -0.6 } },
      { text: '心随流去', gloss: '水去无痕，心亦如是', primary: { traitId: 9, delta: 0.6 } },
    ],
  },
  {
    id: 'esci-r14',
    format: 'ranking',
    prompt: '释疑四径',
    promptGloss: '遇有未解之惑，以何者为先？',
    options: [
      { text: '博览群书', gloss: '以典籍为据', primary: { traitId: 10, delta: -0.6 } },
      { text: '验之以器', gloss: '以实验为法', primary: { traitId: 10, delta: 0.6 } },
      { text: '访师问友', gloss: '以切磋为径', primary: { traitId: 10, delta: -0.2 } },
      { text: '静思冥想', gloss: '以静思为归', primary: { traitId: 10, delta: 0.8 } },
      { text: '四者并用', gloss: '并行不悖', primary: { traitId: 10, delta: 0.0 } },
      { text: '先验后思', gloss: '先试验而后思', primary: { traitId: 10, delta: 0.4 } },
    ],
  },
  {
    id: 'esci-a13',
    format: 'aesthetic',
    prompt: '静室焚香与登高望远',
    promptGloss: '静室焚香之专注与登高望远之开阔，求学之境，何者更美？',
    options: [
      { text: '前者', gloss: '前者更合心意', primary: { traitId: 3, delta: 1.2 } },
      { text: '偏前者', gloss: '略偏前者之境', primary: { traitId: 3, delta: 0.6 }, secondary: [{ traitId: 6, delta: 0.2 }] },
      { text: '兼爱之', gloss: '两种意境皆有可取', primary: { traitId: 3, delta: 0.0 }, secondary: [{ traitId: 6, delta: 0.3 }] },
      { text: '偏后者', gloss: '略偏后者之境', primary: { traitId: 3, delta: -0.6 }, secondary: [{ traitId: 6, delta: -0.2 }] },
      { text: '后者', gloss: '后者更入君心', primary: { traitId: 3, delta: -1.2 } },
      { text: '皆不取', gloss: '超乎二者之外', primary: { traitId: 3, delta: -1.4 }, secondary: [{ traitId: 1, delta: 0.2 }] },
    ],
  },
  {
    id: 'esci-r15',
    format: 'ranking',
    prompt: '验物五序',
    promptGloss: '「形、质、用、数、理」── 验物五序，何者为先？',
    options: [
      { text: '观其形', gloss: '先察其形貌', primary: { traitId: 1, delta: -0.6 } },
      { text: '究其质', gloss: '再究其质料', primary: { traitId: 1, delta: -0.2 } },
      { text: '考其用', gloss: '考察功用', primary: { traitId: 1, delta: 0.4 } },
      { text: '度其数', gloss: '以数衡之', primary: { traitId: 1, delta: 0.8 } },
      { text: '达其理', gloss: '通达其理', primary: { traitId: 1, delta: 1.2 } },
      { text: '五者并进', gloss: '兼而用之', primary: { traitId: 1, delta: 0.0 } },
    ],
  },
  {
    id: 'esci-a14',
    format: 'aesthetic',
    prompt: '晨钟暮鼓与午夜孤灯',
    promptGloss: '晨钟暮鼓之规律与午夜孤灯之专注，求知之景，何者更动人？',
    options: [
      { text: '前者', gloss: '前者更合心意', primary: { traitId: 8, delta: 1.2 } },
      { text: '偏前者', gloss: '略偏前者之境', primary: { traitId: 8, delta: 0.6 }, secondary: [{ traitId: 6, delta: 0.2 }] },
      { text: '兼爱之', gloss: '两种意境皆有可取', primary: { traitId: 8, delta: 0.0 }, secondary: [{ traitId: 6, delta: 0.3 }] },
      { text: '偏后者', gloss: '略偏后者之境', primary: { traitId: 8, delta: -0.6 }, secondary: [{ traitId: 6, delta: -0.2 }] },
      { text: '后者', gloss: '后者更入君心', primary: { traitId: 8, delta: -1.2 } },
      { text: '皆不取', gloss: '超乎二者之外', primary: { traitId: 8, delta: -1.4 }, secondary: [{ traitId: 1, delta: 0.2 }] },
    ],
  },
];
