// 指南 · 文哲巨擘（西方）· 48 题
// 12 维 × 4 题；侧重思辨 / 表达 / 意志 / 革新的哲学语感
// 注：每题设 1 个 primary delta = 0 的中性锚点选项，代表不偏不倚，属有意设计

import type { Item } from './item.types';

export const ITEMS_WEST_PHILOSOPHER: readonly Item[] = [
  // ── T1 思辨 ──
  {
    id: 'wp-r01',
    format: 'ranking',
    prompt: '求知之道',
    promptGloss: '「经验、理性、直觉、信仰」── 求知之道，汝信何者？',
    options: [
      { text: '经验为基', gloss: '以验为知', primary: { traitId: 1, delta: -0.8 } },
      { text: '理性为归', gloss: '以理为宗', primary: { traitId: 1, delta: 0.8 } },
      { text: '直觉为先', gloss: '以悟为知', primary: { traitId: 1, delta: 0.4 } },
      { text: '信仰为凭', gloss: '以信为据', primary: { traitId: 1, delta: -0.4 } },
      { text: '诸法并重', gloss: '兼用为上', primary: { traitId: 1, delta: 0 } },
      { text: '穷理至极', gloss: '至极为度', primary: { traitId: 1, delta: 1.2 } },
    ],
  },
  {
    id: 'wp-a01',
    format: 'aesthetic',
    prompt: '洞穴与日升',
    promptGloss: '洞穴之影与日升之光，两种真理之境，何者更动汝心？',
    options: [
      { text: '前者', gloss: '前者更合心意', primary: { traitId: 1, delta: 1.2 } },
      { text: '偏前者', gloss: '略偏前者之境', primary: { traitId: 1, delta: 0.6 }, secondary: [{ traitId: 6, delta: 0.2 }] },
      { text: '兼爱之', gloss: '两种意境皆有可取', primary: { traitId: 1, delta: 0 }, secondary: [{ traitId: 6, delta: 0.3 }] },
      { text: '偏后者', gloss: '略偏后者之境', primary: { traitId: 1, delta: -0.6 }, secondary: [{ traitId: 6, delta: -0.2 }] },
      { text: '后者', gloss: '后者更入君心', primary: { traitId: 1, delta: -1.2 } },
      { text: '皆不取', gloss: '超乎二者之外', primary: { traitId: 1, delta: -1.4 }, secondary: [{ traitId: 1, delta: 0.2 }] },
    ],
  },
  {
    id: 'wp-003',
    format: 'imagery',
    prompt: '洞穴之光',
    promptGloss: '汝居于可见之影，抑或奔向可知之光？',
    options: [
      { text: '安于影中', gloss: '不求其上', primary: { traitId: 1, delta: -1.2 } },
      { text: '偶窥其光', gloss: '半醒半寐', primary: { traitId: 1, delta: -0.4 } },
      { text: '知其有光', gloss: '知而未往', primary: { traitId: 1, delta: 0.0 } },
      { text: '转身向光', gloss: '知而求之', primary: { traitId: 1, delta: 1.0 } },
      {
        text: '出洞穴',
        gloss: '走向可知之光',
        primary: { traitId: 1, delta: 1.2 },
        secondary: [{ traitId: 4, delta: 0.4 }],
      },
      {
        text: '反身救人',
        gloss: '由明返暗',
        primary: { traitId: 1, delta: 1.4 },
        secondary: [{ traitId: 5, delta: 0.4 }],
      },
    ],
  },
  {
    id: 'wp-004',
    format: 'situational',
    prompt: '抽象与具体',
    promptGloss: '汝更信何种思维？',
    options: [
      { text: '唯具体', gloss: '以触为真', primary: { traitId: 1, delta: -1.4 } },
      { text: '重具体', gloss: '以验为基', primary: { traitId: 1, delta: -0.6 } },
      { text: '兼取之', gloss: '相辅为用', primary: { traitId: 1, delta: 0.0 } },
      { text: '重抽象', gloss: '以理为度', primary: { traitId: 1, delta: 0.6 } },
      { text: '唯抽象', gloss: '形而上之', primary: { traitId: 1, delta: 1.2 } },
      { text: '形而上之', gloss: '以绝对为度', primary: { traitId: 1, delta: 1.4 } },
    ],
  },

  // ── T2 情感 ──
  {
    id: 'wp-r02',
    format: 'ranking',
    prompt: '心灵之境',
    promptGloss: '「静观、激情、仁爱、狂醉」── 心灵境界，何者最真？',
    options: [
      { text: '澄怀静观', gloss: '以静为深', primary: { traitId: 2, delta: -0.8 } },
      { text: '激情澎湃', gloss: '以情为真', primary: { traitId: 2, delta: 1 } },
      { text: '仁爱为怀', gloss: '以爱为度', primary: { traitId: 2, delta: 0.4 } },
      { text: '狂醉为达', gloss: '以狂为径', primary: { traitId: 2, delta: 1.4 } },
      { text: '以中为度', gloss: '不偏不倚', primary: { traitId: 2, delta: 0 } },
      { text: '哀矜勿喜', gloss: '以悲为本', primary: { traitId: 2, delta: 0.8 } },
    ],
  },
  {
    id: 'wp-a02',
    format: 'aesthetic',
    prompt: '日神与酒神',
    promptGloss: '日神之秩序与酒神之狂醉，两种生命精神，何者更契？',
    options: [
      { text: '前者', gloss: '前者更合心意', primary: { traitId: 2, delta: 1.2 } },
      { text: '偏前者', gloss: '略偏前者之境', primary: { traitId: 2, delta: 0.6 }, secondary: [{ traitId: 6, delta: 0.2 }] },
      { text: '兼爱之', gloss: '两种意境皆有可取', primary: { traitId: 2, delta: 0 }, secondary: [{ traitId: 6, delta: 0.3 }] },
      { text: '偏后者', gloss: '略偏后者之境', primary: { traitId: 2, delta: -0.6 }, secondary: [{ traitId: 6, delta: -0.2 }] },
      { text: '后者', gloss: '后者更入君心', primary: { traitId: 2, delta: -1.2 } },
      { text: '皆不取', gloss: '超乎二者之外', primary: { traitId: 2, delta: -1.4 }, secondary: [{ traitId: 1, delta: 0.2 }] },
    ],
  },
  {
    id: 'wp-007',
    format: 'imagery',
    prompt: '冷月与烈火',
    promptGloss: '汝之心性，更近何象？',
    options: [
      { text: '寒冰', gloss: '以冷为度', primary: { traitId: 2, delta: -1.2 } },
      { text: '冷月', gloss: '清而不热', primary: { traitId: 2, delta: -0.6 } },
      { text: '晨光', gloss: '温而不烈', primary: { traitId: 2, delta: 0.0 } },
      { text: '炉火', gloss: '温而持久', primary: { traitId: 2, delta: 0.6 } },
      { text: '烈焰', gloss: '以热为真', primary: { traitId: 2, delta: 1.2 } },
      { text: '火山', gloss: '以炽为道', primary: { traitId: 2, delta: 1.4 } },
    ],
  },
  {
    id: 'wp-008',
    format: 'situational',
    prompt: '爱之形',
    promptGloss: '汝之爱，更倾何方？',
    options: [
      {
        text: '智性之爱',
        gloss: '柏拉图之径',
        primary: { traitId: 2, delta: -0.6 },
        secondary: [{ traitId: 1, delta: 0.4 }],
      },
      {
        text: '友爱之爱',
        gloss: '亚里士多德之径',
        primary: { traitId: 2, delta: 0.0 },
        secondary: [{ traitId: 5, delta: 0.3 }],
      },
      {
        text: '怜悯之爱',
        gloss: '以慈为度',
        primary: { traitId: 2, delta: 0.6 },
        secondary: [{ traitId: 5, delta: 0.3 }],
      },
      { text: '激情之爱', gloss: '以恋为真', primary: { traitId: 2, delta: 1.0 } },
      { text: '忘我之爱', gloss: '以舍为度', primary: { traitId: 2, delta: 1.2 } },
      {
        text: '神性之爱',
        gloss: '以圣为度',
        primary: { traitId: 2, delta: 1.4 },
        secondary: [{ traitId: 9, delta: 0.4 }],
      },
    ],
  },

  // ── T3 行动 ──
  {
    id: 'wp-r03',
    format: 'ranking',
    prompt: '介入之式',
    promptGloss: '「旁观、立言、行动、殉道」── 践行哲学，何者为先？',
    options: [
      { text: '旁观静察', gloss: '静观为度', primary: { traitId: 3, delta: -1 } },
      { text: '立言为教', gloss: '以言为行', primary: { traitId: 3, delta: 0.4 } },
      { text: '奋起而行', gloss: '以行为真', primary: { traitId: 3, delta: 1.2 } },
      { text: '以身殉道', gloss: '以死为证', primary: { traitId: 3, delta: 1.4 } },
      { text: '不偏不执', gloss: '以中为度', primary: { traitId: 3, delta: 0 } },
      { text: '以笔为剑', gloss: '以文为器', primary: { traitId: 3, delta: 0.8 } },
    ],
  },
  {
    id: 'wp-010',
    format: 'situational',
    prompt: '时机之问',
    promptGloss: '机不可失，汝如何行？',
    options: [
      { text: '待其自至', gloss: '以静为度', primary: { traitId: 3, delta: -1.0 } },
      { text: '徐徐待之', gloss: '不争于时', primary: { traitId: 3, delta: -0.4 } },
      { text: '从容而行', gloss: '不急不缓', primary: { traitId: 3, delta: 0.2 } },
      {
        text: '即断即行',
        gloss: '雷厉风行',
        primary: { traitId: 3, delta: 1.0 },
        secondary: [{ traitId: 7, delta: 0.3 }],
      },
      { text: '先发制人', gloss: '主动而出', primary: { traitId: 3, delta: 1.2 } },
      { text: '当机立断', gloss: '不容犹豫', primary: { traitId: 3, delta: 1.4 } },
    ],
  },
  {
    id: 'wp-011',
    format: 'imagery',
    prompt: '思想之锋',
    promptGloss: '传播哲思，汝倾锋刃抑或润物？',
    options: [
      { text: '静水', gloss: '以静为深', primary: { traitId: 3, delta: -0.8 } },
      { text: '缓流', gloss: '以缓为度', primary: { traitId: 3, delta: -0.2 } },
      { text: '常流', gloss: '以常为节', primary: { traitId: 3, delta: 0.2 } },
      { text: '疾风', gloss: '以疾为节', primary: { traitId: 3, delta: 0.8 } },
      { text: '雷霆', gloss: '以雷为节', primary: { traitId: 3, delta: 1.2 } },
      { text: '闪电', gloss: '一击即发', primary: { traitId: 3, delta: 1.4 } },
    ],
  },
  {
    id: 'wp-012',
    format: 'situational',
    prompt: '思与行',
    promptGloss: '思久而不行，汝当何为？',
    options: [
      { text: '不求行', gloss: '以思为足', primary: { traitId: 3, delta: -1.2 } },
      {
        text: '思而不倦',
        gloss: '以思为道',
        primary: { traitId: 3, delta: -0.4 },
        secondary: [{ traitId: 1, delta: 0.3 }],
      },
      { text: '思而时行', gloss: '以时为度', primary: { traitId: 3, delta: 0.2 } },
      { text: '行而不怠', gloss: '以行为真', primary: { traitId: 3, delta: 1.0 } },
      { text: '先行后思', gloss: '以行证思', primary: { traitId: 3, delta: 1.2 } },
      { text: '即思即行', gloss: '思行合一', primary: { traitId: 3, delta: 1.4 } },
    ],
  },

  // ── T4 革新 ──
  {
    id: 'wp-r04',
    format: 'ranking',
    prompt: '传统之序',
    promptGloss: '「传承、改良、颠覆、重估」── 面对传统，何者为上？',
    options: [
      { text: '传承为本', gloss: '以古为师', primary: { traitId: 4, delta: -1.2 } },
      { text: '渐改为上', gloss: '以变为进', primary: { traitId: 4, delta: -0.4 } },
      { text: '彻底颠覆', gloss: '破而不立', primary: { traitId: 4, delta: 1.2 } },
      { text: '重估一切', gloss: '推倒重来', primary: { traitId: 4, delta: 1.4 } },
      { text: '折中调和', gloss: '以中为度', primary: { traitId: 4, delta: 0 } },
      { text: '以新为是', gloss: '不泥于古', primary: { traitId: 4, delta: 0.8 } },
    ],
  },
  {
    id: 'wp-a04',
    format: 'aesthetic',
    prompt: '废墟与萌芽',
    promptGloss: '旧制废墟之苍凉与新生萌芽之朝气，变革之美，何者更动人？',
    options: [
      { text: '前者', gloss: '前者更合心意', primary: { traitId: 4, delta: 1.2 } },
      { text: '偏前者', gloss: '略偏前者之境', primary: { traitId: 4, delta: 0.6 }, secondary: [{ traitId: 6, delta: 0.2 }] },
      { text: '兼爱之', gloss: '两种意境皆有可取', primary: { traitId: 4, delta: 0 }, secondary: [{ traitId: 6, delta: 0.3 }] },
      { text: '偏后者', gloss: '略偏后者之境', primary: { traitId: 4, delta: -0.6 }, secondary: [{ traitId: 6, delta: -0.2 }] },
      { text: '后者', gloss: '后者更入君心', primary: { traitId: 4, delta: -1.2 } },
      { text: '皆不取', gloss: '超乎二者之外', primary: { traitId: 4, delta: -1.4 }, secondary: [{ traitId: 1, delta: 0.2 }] },
    ],
  },
  {
    id: 'wp-015',
    format: 'imagery',
    prompt: '新瓶与旧酒',
    promptGloss: '汝更倾何喻？',
    options: [
      { text: '唯旧', gloss: '以古为美', primary: { traitId: 4, delta: -1.2 } },
      { text: '旧主新辅', gloss: '以古为体', primary: { traitId: 4, delta: -0.4 } },
      { text: '新旧并存', gloss: '相辅相成', primary: { traitId: 4, delta: 0.2 } },
      { text: '新主旧辅', gloss: '以新为用', primary: { traitId: 4, delta: 0.8 } },
      { text: '唯新', gloss: '以新为美', primary: { traitId: 4, delta: 1.2 } },
      { text: '破瓶', gloss: '不立任何', primary: { traitId: 4, delta: 1.4 } },
    ],
  },
  {
    id: 'wp-016',
    format: 'situational',
    prompt: '破神之问',
    promptGloss: '若神已死，汝将何以立？',
    options: [
      { text: '神永在', gloss: '信而不疑', primary: { traitId: 4, delta: -1.4 } },
      { text: '神虽死', gloss: '道德不泯', primary: { traitId: 4, delta: -0.4 } },
      { text: '以礼代神', gloss: '以俗为度', primary: { traitId: 4, delta: 0.0 } },
      { text: '自我立法', gloss: '尼采之径', primary: { traitId: 4, delta: 1.0 } },
      { text: '超人而出', gloss: '以超人为本', primary: { traitId: 4, delta: 1.2 } },
      { text: '重估一切', gloss: '以锤为准', primary: { traitId: 4, delta: 1.4 } },
    ],
  },

  // ── T5 群我 ──
  {
    id: 'wp-r05',
    format: 'ranking',
    prompt: '思想之域',
    promptGloss: '「独我、群伦、天下、万世」── 思想所属，何者最重？',
    options: [
      { text: '独我先立', gloss: '以己为度', primary: { traitId: 5, delta: -1.2 } },
      { text: '群伦为先', gloss: '以众为度', primary: { traitId: 5, delta: 0.8 } },
      { text: '天下为怀', gloss: '以天下为度', primary: { traitId: 5, delta: 1.2 } },
      { text: '万世为念', gloss: '以永为度', primary: { traitId: 5, delta: 1.4 } },
      { text: '因事而择', gloss: '不执一端', primary: { traitId: 5, delta: 0 } },
      { text: '为他者言', gloss: '为他而存', primary: { traitId: 5, delta: 1 } },
    ],
  },
  {
    id: 'wp-a05',
    format: 'aesthetic',
    prompt: '独白与交响',
    promptGloss: '一人独白与万物交响，思想之声，何者更契汝心？',
    options: [
      { text: '前者', gloss: '前者更合心意', primary: { traitId: 5, delta: 1.2 } },
      { text: '偏前者', gloss: '略偏前者之境', primary: { traitId: 5, delta: 0.6 }, secondary: [{ traitId: 6, delta: 0.2 }] },
      { text: '兼爱之', gloss: '两种意境皆有可取', primary: { traitId: 5, delta: 0 }, secondary: [{ traitId: 6, delta: 0.3 }] },
      { text: '偏后者', gloss: '略偏后者之境', primary: { traitId: 5, delta: -0.6 }, secondary: [{ traitId: 6, delta: -0.2 }] },
      { text: '后者', gloss: '后者更入君心', primary: { traitId: 5, delta: -1.2 } },
      { text: '皆不取', gloss: '超乎二者之外', primary: { traitId: 5, delta: -1.4 }, secondary: [{ traitId: 1, delta: 0.2 }] },
    ],
  },
  {
    id: 'wp-019',
    format: 'imagery',
    prompt: '独思与统',
    promptGloss: '哲学立言，更重独出己意或承继道统？',
    options: [
      { text: '独木', gloss: '以一为度', primary: { traitId: 5, delta: -1.2 } },
      { text: '双木', gloss: '以友为度', primary: { traitId: 5, delta: -0.4 } },
      { text: '木与林', gloss: '兼己与群', primary: { traitId: 5, delta: 0.2 } },
      { text: '森林', gloss: '以群为度', primary: { traitId: 5, delta: 0.8 } },
      { text: '众生一体', gloss: '以共为度', primary: { traitId: 5, delta: 1.2 } },
      { text: '万物相连', gloss: '以通为度', primary: { traitId: 5, delta: 1.4 } },
    ],
  },
  {
    id: 'wp-020',
    format: 'situational',
    prompt: '启蒙之任',
    promptGloss: '若世人蒙昧，汝当如何？',
    options: [
      { text: '听其自然', gloss: '不强为人', primary: { traitId: 5, delta: -1.2 } },
      { text: '独善其身', gloss: '以己为足', primary: { traitId: 5, delta: -0.4 } },
      { text: '随缘而教', gloss: '不求广度', primary: { traitId: 5, delta: 0.0 } },
      { text: '立说传道', gloss: '以教为度', primary: { traitId: 5, delta: 0.8 } },
      { text: '开启民智', gloss: '启蒙之径', primary: { traitId: 5, delta: 1.2 } },
      { text: '为万世开太平', gloss: '以永为度', primary: { traitId: 5, delta: 1.4 } },
    ],
  },

  // ── T6 审美 ──
  {
    id: 'wp-021',
    format: 'imagery',
    prompt: '美之所向',
    promptGloss: '美之于汝，更近何象？',
    options: [
      { text: '几何', gloss: '以数为美', primary: { traitId: 6, delta: -1.0 } },
      { text: '对称', gloss: '以序为美', primary: { traitId: 6, delta: -0.4 } },
      { text: '和谐', gloss: '以中为美', primary: { traitId: 6, delta: 0.0 } },
      { text: '崇高', gloss: '以大为美', primary: { traitId: 6, delta: 0.8 } },
      { text: '悲剧', gloss: '以痛为美', primary: { traitId: 6, delta: 1.2 } },
      { text: '荒诞', gloss: '加缪之径', primary: { traitId: 6, delta: 1.4 } },
    ],
  },
  {
    id: 'wp-r06',
    format: 'ranking',
    prompt: '美之境界',
    promptGloss: '「和谐、崇高、悲剧、荒诞」── 美的境界，何者最动汝？',
    options: [
      { text: '和谐为美', gloss: '以和为美', primary: { traitId: 6, delta: -0.6 } },
      { text: '崇高为上', gloss: '以大为美', primary: { traitId: 6, delta: 0.4 } },
      { text: '悲剧之深', gloss: '以悲为美', primary: { traitId: 6, delta: 1 } },
      { text: '荒诞之真', gloss: '以荒谬为美', primary: { traitId: 6, delta: 1.4 } },
      { text: '皆有所美', gloss: '不拘一格', primary: { traitId: 6, delta: 0 } },
      { text: '无美无丑', gloss: '超越美丑', primary: { traitId: 6, delta: -0.4 } },
    ],
  },
  {
    id: 'wp-a06',
    format: 'aesthetic',
    prompt: '残缺与完整',
    promptGloss: '维纳斯之断臂与完美之雕像，何者更见美的本质？',
    options: [
      { text: '前者', gloss: '前者更合心意', primary: { traitId: 6, delta: 1.2 } },
      { text: '偏前者', gloss: '略偏前者之境', primary: { traitId: 6, delta: 0.6 }, secondary: [{ traitId: 6, delta: 0.2 }] },
      { text: '兼爱之', gloss: '两种意境皆有可取', primary: { traitId: 6, delta: 0 }, secondary: [{ traitId: 6, delta: 0.3 }] },
      { text: '偏后者', gloss: '略偏后者之境', primary: { traitId: 6, delta: -0.6 }, secondary: [{ traitId: 6, delta: -0.2 }] },
      { text: '后者', gloss: '后者更入君心', primary: { traitId: 6, delta: -1.2 } },
      { text: '皆不取', gloss: '超乎二者之外', primary: { traitId: 6, delta: -1.4 }, secondary: [{ traitId: 1, delta: 0.2 }] },
    ],
  },
  {
    id: 'wp-024',
    format: 'imagery',
    prompt: '音乐之境',
    promptGloss: '听乐，汝更入何境？',
    options: [
      { text: '寂', gloss: '以静为度', primary: { traitId: 6, delta: -1.0 } },
      { text: '净', gloss: '以纯为度', primary: { traitId: 6, delta: -0.4 } },
      { text: '和', gloss: '以和为度', primary: { traitId: 6, delta: 0.0 } },
      { text: '壮', gloss: '以壮为度', primary: { traitId: 6, delta: 0.6 } },
      { text: '悲', gloss: '以悲为度', primary: { traitId: 6, delta: 1.0 } },
      { text: '醉', gloss: '以醉为度', primary: { traitId: 6, delta: 1.2 } },
    ],
  },

  // ── T7 意志 ──
  {
    id: 'wp-r07',
    format: 'ranking',
    prompt: '逆境之柱',
    promptGloss: '「信仰、理性、意志、绝望」── 逆境之柱，何者最坚？',
    options: [
      { text: '信仰为灯', gloss: '以信为坚', primary: { traitId: 7, delta: 0.6 } },
      { text: '理性为舟', gloss: '以理为力', primary: { traitId: 7, delta: 0.4 } },
      { text: '意志为剑', gloss: '以志为刃', primary: { traitId: 7, delta: 1.2 } },
      { text: '绝望为勇', gloss: '以绝望为度', primary: { traitId: 7, delta: 1.4 } },
      { text: '顺其自然', gloss: '不强求', primary: { traitId: 7, delta: -0.6 } },
      { text: '坦然承受', gloss: '以承受为度', primary: { traitId: 7, delta: -0.2 } },
    ],
  },
  {
    id: 'wp-026',
    format: 'situational',
    prompt: '孤独之问',
    promptGloss: '众人皆醉，汝独醒，何以处？',
    options: [
      { text: '随之而醉', gloss: '以同为度', primary: { traitId: 7, delta: -1.4 } },
      { text: '随而不醉', gloss: '以同为度', primary: { traitId: 7, delta: -0.4 } },
      { text: '不与争', gloss: '不与之较', primary: { traitId: 7, delta: 0.0 } },
      { text: '独守其明', gloss: '以独为度', primary: { traitId: 7, delta: 0.8 } },
      { text: '劝之使醒', gloss: '苏格拉底之径', primary: { traitId: 7, delta: 1.0 } },
      { text: '以死殉道', gloss: '以死为度', primary: { traitId: 7, delta: 1.4 } },
    ],
  },
  {
    id: 'wp-027',
    format: 'imagery',
    prompt: '命运之绳',
    promptGloss: '意志之于命运，汝更信何方？',
    options: [
      { text: '唯命运', gloss: '以命为度', primary: { traitId: 7, delta: -1.4 } },
      { text: '命主志辅', gloss: '以命为体', primary: { traitId: 7, delta: -0.4 } },
      { text: '相半', gloss: '以半为度', primary: { traitId: 7, delta: 0.0 } },
      { text: '志主命辅', gloss: '以志为体', primary: { traitId: 7, delta: 0.8 } },
      { text: '唯意志', gloss: '叔本华之径', primary: { traitId: 7, delta: 1.2 } },
      { text: '超善恶', gloss: '尼采之径', primary: { traitId: 7, delta: 1.4 } },
    ],
  },
  {
    id: 'wp-028',
    format: 'situational',
    prompt: '信与疑',
    promptGloss: '当理性之穷处，汝何以立？',
    options: [
      { text: '只信理', gloss: '以理为度', primary: { traitId: 7, delta: -1.0 } },
      { text: '信多于疑', gloss: '以信为度', primary: { traitId: 7, delta: -0.4 } },
      { text: '因事而择', gloss: '不强求', primary: { traitId: 7, delta: 0.0 } },
      { text: '信而有疑', gloss: '以诚为度', primary: { traitId: 7, delta: 0.6 } },
      { text: '信仰之跃', gloss: '克尔凯郭尔之径', primary: { traitId: 7, delta: 1.2 } },
      { text: '信而无疑', gloss: '以信为真', primary: { traitId: 7, delta: 1.4 } },
    ],
  },

  // ── T8 学识 ──
  {
    id: 'wp-r08',
    format: 'ranking',
    prompt: '学问之阶',
    promptGloss: '「感觉、经验、概念、先验」── 学问之阶，何者最基？',
    options: [
      { text: '感觉为本', gloss: '以感为基', primary: { traitId: 8, delta: -0.8 } },
      { text: '经验为用', gloss: '以验为基', primary: { traitId: 8, delta: -0.4 } },
      { text: '概念为器', gloss: '以理为基', primary: { traitId: 8, delta: 0.6 } },
      { text: '先验为归', gloss: '以先为度', primary: { traitId: 8, delta: 1.2 } },
      { text: '兼取诸法', gloss: '兼收并蓄', primary: { traitId: 8, delta: 0 } },
      { text: '以用为度', gloss: '择宜而从', primary: { traitId: 8, delta: 0.4 } },
    ],
  },
  {
    id: 'wp-a08',
    format: 'aesthetic',
    prompt: '迷宫与神殿',
    promptGloss: '迷宫之曲折与神殿之庄严，认知之路，何景更美？',
    options: [
      { text: '前者', gloss: '前者更合心意', primary: { traitId: 8, delta: 1.2 } },
      { text: '偏前者', gloss: '略偏前者之境', primary: { traitId: 8, delta: 0.6 }, secondary: [{ traitId: 6, delta: 0.2 }] },
      { text: '兼爱之', gloss: '两种意境皆有可取', primary: { traitId: 8, delta: 0 }, secondary: [{ traitId: 6, delta: 0.3 }] },
      { text: '偏后者', gloss: '略偏后者之境', primary: { traitId: 8, delta: -0.6 }, secondary: [{ traitId: 6, delta: -0.2 }] },
      { text: '后者', gloss: '后者更入君心', primary: { traitId: 8, delta: -1.2 } },
      { text: '皆不取', gloss: '超乎二者之外', primary: { traitId: 8, delta: -1.4 }, secondary: [{ traitId: 1, delta: 0.2 }] },
    ],
  },
  {
    id: 'wp-031',
    format: 'imagery',
    prompt: '学问之器',
    promptGloss: '学问之于汝，更近何器？',
    options: [
      { text: '井水', gloss: '一隅之知', primary: { traitId: 8, delta: -0.8 } },
      { text: '溪流', gloss: '日积月累', primary: { traitId: 8, delta: -0.2 } },
      { text: '江河', gloss: '以学为江', primary: { traitId: 8, delta: 0.4 } },
      { text: '大江', gloss: '以学为大', primary: { traitId: 8, delta: 0.8 } },
      { text: '海洋', gloss: '以学为海', primary: { traitId: 8, delta: 1.2 } },
      { text: '海与天空', gloss: '以学为天', primary: { traitId: 8, delta: 1.4 } },
    ],
  },
  {
    id: 'wp-032',
    format: 'situational',
    prompt: '哲学之用',
    promptGloss: '思辨之道，汝取无用之用抑或经世致用？',
    options: [
      { text: '不求用', gloss: '以知为足', primary: { traitId: 8, delta: -0.8 } },
      { text: '自修而已', gloss: '以己为度', primary: { traitId: 8, delta: -0.4 } },
      { text: '自用而已', gloss: '以用为度', primary: { traitId: 8, delta: 0.0 } },
      { text: '以学为用', gloss: '培根之径', primary: { traitId: 8, delta: 0.6 } },
      { text: '为人类谋', gloss: '以人为度', primary: { traitId: 8, delta: 1.0 } },
      { text: '为天下立法', gloss: '以法为度', primary: { traitId: 8, delta: 1.2 } },
    ],
  },

  // ── T9 处世 ──
  {
    id: 'wp-r09',
    format: 'ranking',
    prompt: '哲人之路',
    promptGloss: '「入世、批判、退隐、沉默」── 哲人处世，何者为上？',
    options: [
      { text: '积极入世', gloss: '以进为度', primary: { traitId: 9, delta: -1.2 } },
      { text: '批判为任', gloss: '以批为道', primary: { traitId: 9, delta: -0.4 } },
      { text: '退隐修道', gloss: '退而思之', primary: { traitId: 9, delta: 0.8 } },
      { text: '沉默为金', gloss: '以默为归', primary: { traitId: 9, delta: 1.4 } },
      { text: '行藏以时', gloss: '审时而动', primary: { traitId: 9, delta: 0 } },
      { text: '半入半隐', gloss: '两兼其中', primary: { traitId: 9, delta: 0.4 } },
    ],
  },
  {
    id: 'wp-a09',
    format: 'aesthetic',
    prompt: '白杨与古松',
    promptGloss: '白杨之挺拔与古松之虬曲，哲人形象，何者更入汝心？',
    options: [
      { text: '前者', gloss: '前者更合心意', primary: { traitId: 9, delta: 1.2 } },
      { text: '偏前者', gloss: '略偏前者之境', primary: { traitId: 9, delta: 0.6 }, secondary: [{ traitId: 6, delta: 0.2 }] },
      { text: '兼爱之', gloss: '两种意境皆有可取', primary: { traitId: 9, delta: 0 }, secondary: [{ traitId: 6, delta: 0.3 }] },
      { text: '偏后者', gloss: '略偏后者之境', primary: { traitId: 9, delta: -0.6 }, secondary: [{ traitId: 6, delta: -0.2 }] },
      { text: '后者', gloss: '后者更入君心', primary: { traitId: 9, delta: -1.2 } },
      { text: '皆不取', gloss: '超乎二者之外', primary: { traitId: 9, delta: -1.4 }, secondary: [{ traitId: 1, delta: 0.2 }] },
    ],
  },
  {
    id: 'wp-035',
    format: 'imagery',
    prompt: '塔与井',
    promptGloss: '思想者于世，更近何象？',
    options: [
      { text: '井底', gloss: '以深为度', primary: { traitId: 9, delta: -1.4 } },
      { text: '井中', gloss: '以中为度', primary: { traitId: 9, delta: -0.4 } },
      { text: '平地', gloss: '以平为度', primary: { traitId: 9, delta: 0.2 } },
      { text: '塔下', gloss: '以立为度', primary: { traitId: 9, delta: 0.8 } },
      { text: '塔中', gloss: '以望为度', primary: { traitId: 9, delta: 1.2 } },
      { text: '塔顶', gloss: '以高为度', primary: { traitId: 9, delta: 1.4 } },
    ],
  },
  {
    id: 'wp-036',
    format: 'situational',
    prompt: '思想之秋',
    promptGloss: '思想生命，汝更重早岁锋芒抑或暮秋深沉？',
    options: [
      { text: '老骥伏枥', gloss: '以志为老', primary: { traitId: 9, delta: -1.0 } },
      { text: '仍有所为', gloss: '以行为老', primary: { traitId: 9, delta: -0.4 } },
      { text: '不急不缓', gloss: '以中为度', primary: { traitId: 9, delta: 0.2 } },
      { text: '退而思之', gloss: '以退为老', primary: { traitId: 9, delta: 0.8 } },
      { text: '传道授业', gloss: '以传为老', primary: { traitId: 9, delta: 1.2 } },
      { text: '归于无言', gloss: '以无言为度', primary: { traitId: 9, delta: 1.4 } },
    ],
  },

  // ── T10 时间 ──
  {
    id: 'wp-r10',
    format: 'ranking',
    prompt: '时间之思',
    promptGloss: '「瞬间、绵延、永恒、轮回」── 时间之思，何者最契？',
    options: [
      { text: '活在瞬间', gloss: '以刹那为真', primary: { traitId: 10, delta: -1 } },
      { text: '绵延为渡', gloss: '以续为真', primary: { traitId: 10, delta: -0.2 } },
      { text: '永恒为归', gloss: '以永为真', primary: { traitId: 10, delta: 1 } },
      { text: '永恒轮回', gloss: '以轮回为真', primary: { traitId: 10, delta: 1.4 } },
      { text: '不执于时', gloss: '超乎时间', primary: { traitId: 10, delta: 0.2 } },
      { text: '活在当下', gloss: '以今为足', primary: { traitId: 10, delta: -0.6 } },
    ],
  },
  {
    id: 'wp-a10',
    format: 'aesthetic',
    prompt: '飞矢与圆环',
    promptGloss: '飞矢之直进与圆环之回转，时间象喻，何者更契？',
    options: [
      { text: '前者', gloss: '前者更合心意', primary: { traitId: 10, delta: 1.2 } },
      { text: '偏前者', gloss: '略偏前者之境', primary: { traitId: 10, delta: 0.6 }, secondary: [{ traitId: 6, delta: 0.2 }] },
      { text: '兼爱之', gloss: '两种意境皆有可取', primary: { traitId: 10, delta: 0 }, secondary: [{ traitId: 6, delta: 0.3 }] },
      { text: '偏后者', gloss: '略偏后者之境', primary: { traitId: 10, delta: -0.6 }, secondary: [{ traitId: 6, delta: -0.2 }] },
      { text: '后者', gloss: '后者更入君心', primary: { traitId: 10, delta: -1.2 } },
      { text: '皆不取', gloss: '超乎二者之外', primary: { traitId: 10, delta: -1.4 }, secondary: [{ traitId: 1, delta: 0.2 }] },
    ],
  },
  {
    id: 'wp-039',
    format: 'imagery',
    prompt: '时间之问',
    promptGloss: '汝之时间，更近何喻？',
    options: [
      { text: '直线', gloss: '以直为度', primary: { traitId: 10, delta: -0.8 } },
      { text: '流水', gloss: '以流为度', primary: { traitId: 10, delta: -0.4 } },
      { text: '绵延', gloss: '柏格森之径', primary: { traitId: 10, delta: 0.6 } },
      { text: '圆环', gloss: '以环为度', primary: { traitId: 10, delta: 1.0 } },
      { text: '星丛', gloss: '本雅明之径', primary: { traitId: 10, delta: 1.2 } },
      { text: '永恒之今', gloss: '奥古斯丁之径', primary: { traitId: 10, delta: 1.4 } },
    ],
  },
  {
    id: 'wp-040',
    format: 'situational',
    prompt: '思想之嗣',
    promptGloss: '汝之哲思，愿传世为嗣抑或不求身后之名？',
    options: [
      { text: '不计身后', gloss: '以生为度', primary: { traitId: 10, delta: -1.2 } },
      { text: '随其自至', gloss: '不求之', primary: { traitId: 10, delta: -0.4 } },
      { text: '求当世名', gloss: '以当为度', primary: { traitId: 10, delta: 0.0 } },
      { text: '求百世名', gloss: '以百为度', primary: { traitId: 10, delta: 0.8 } },
      { text: '求千世名', gloss: '以千为度', primary: { traitId: 10, delta: 1.2 } },
      { text: '名与身齐', gloss: '以一为度', primary: { traitId: 10, delta: 1.4 } },
    ],
  },

  // ── T11 风险 ──
  {
    id: 'wp-r11',
    format: 'ranking',
    prompt: '真理之价',
    promptGloss: '「安逸、风险、牺牲、殉道」── 求真理之价，汝付何者？',
    options: [
      { text: '以求安逸', gloss: '以安为度', primary: { traitId: 11, delta: -1.4 } },
      { text: '甘冒风险', gloss: '以险为渡', primary: { traitId: 11, delta: 0.6 } },
      { text: '勇于牺牲', gloss: '以舍为取', primary: { traitId: 11, delta: 1 } },
      { text: '以身殉真', gloss: '以死为证', primary: { traitId: 11, delta: 1.4 } },
      { text: '不偏不倚', gloss: '折中为上', primary: { traitId: 11, delta: 0 } },
      { text: '见机而进', gloss: '伺机而行', primary: { traitId: 11, delta: 0.4 } },
    ],
  },
  {
    id: 'wp-a11',
    format: 'aesthetic',
    prompt: '晨露与深渊',
    promptGloss: '晨露之晶莹与深渊之幽暗，两种存在之态，何者更动人？',
    options: [
      { text: '前者', gloss: '前者更合心意', primary: { traitId: 11, delta: 1.2 } },
      { text: '偏前者', gloss: '略偏前者之境', primary: { traitId: 11, delta: 0.6 }, secondary: [{ traitId: 6, delta: 0.2 }] },
      { text: '兼爱之', gloss: '两种意境皆有可取', primary: { traitId: 11, delta: 0 }, secondary: [{ traitId: 6, delta: 0.3 }] },
      { text: '偏后者', gloss: '略偏后者之境', primary: { traitId: 11, delta: -0.6 }, secondary: [{ traitId: 6, delta: -0.2 }] },
      { text: '后者', gloss: '后者更入君心', primary: { traitId: 11, delta: -1.2 } },
      { text: '皆不取', gloss: '超乎二者之外', primary: { traitId: 11, delta: -1.4 }, secondary: [{ traitId: 1, delta: 0.2 }] },
    ],
  },
  {
    id: 'wp-043',
    format: 'imagery',
    prompt: '航于大海',
    promptGloss: '思想者如行舟，汝更信何方？',
    options: [
      { text: '系于岸', gloss: '以守为锚', primary: { traitId: 11, delta: -1.4 } },
      { text: '近岸行', gloss: '以近为度', primary: { traitId: 11, delta: -0.4 } },
      { text: '随风而动', gloss: '以时为度', primary: { traitId: 11, delta: 0.2 } },
      { text: '远帆而行', gloss: '以远为度', primary: { traitId: 11, delta: 0.8 } },
      { text: '破浪而往', gloss: '以浪为度', primary: { traitId: 11, delta: 1.2 } },
      { text: '穷尽大海', gloss: '以穷为度', primary: { traitId: 11, delta: 1.4 } },
    ],
  },
  {
    id: 'wp-044',
    format: 'situational',
    prompt: '成与败',
    promptGloss: '若所行必败，汝犹行乎？',
    options: [
      { text: '不求必败', gloss: '以安为度', primary: { traitId: 11, delta: -1.4 } },
      { text: '见可而止', gloss: '以止为度', primary: { traitId: 11, delta: -0.4 } },
      { text: '因事而择', gloss: '不强求', primary: { traitId: 11, delta: 0.0 } },
      { text: '虽败犹行', gloss: '以行为度', primary: { traitId: 11, delta: 0.8 } },
      { text: '明知其败', gloss: '以败为度', primary: { traitId: 11, delta: 1.2 } },
      { text: '不悔其行', gloss: '以一为度', primary: { traitId: 11, delta: 1.4 } },
    ],
  },

  // ── T12 表达 ──
  {
    id: 'wp-r12',
    format: 'ranking',
    prompt: '言说之式',
    promptGloss: '「格言、对话、体系、诗化」── 言说之式，何者最擅？',
    options: [
      { text: '格言警世', gloss: '以言为剑', primary: { traitId: 12, delta: 0.4 } },
      { text: '对话启思', gloss: '以对为媒', primary: { traitId: 12, delta: 0 } },
      { text: '体系立言', gloss: '以系为归', primary: { traitId: 12, delta: 0.8 } },
      { text: '诗化哲思', gloss: '以诗为言', primary: { traitId: 12, delta: 1.2 } },
      { text: '质直而言', gloss: '以直为言', primary: { traitId: 12, delta: -0.8 } },
      { text: '不言为言', gloss: '以默为言', primary: { traitId: 12, delta: -0.4 } },
    ],
  },
  {
    id: 'wp-046',
    format: 'situational',
    prompt: '对话与独白',
    promptGloss: '汝之文风，更近何端？',
    options: [
      { text: '格言', gloss: '以言为体', primary: { traitId: 12, delta: -0.8 } },
      { text: '对话', gloss: '以对为体', primary: { traitId: 12, delta: -0.2 } },
      { text: '论述', gloss: '以论为体', primary: { traitId: 12, delta: 0.2 } },
      { text: '散文', gloss: '以散为体', primary: { traitId: 12, delta: 0.6 } },
      { text: '长论', gloss: '以长为体', primary: { traitId: 12, delta: 1.0 } },
      { text: '体系', gloss: '以系为体', primary: { traitId: 12, delta: 1.2 } },
    ],
  },
  {
    id: 'wp-047',
    format: 'imagery',
    prompt: '言为器',
    promptGloss: '言之于汝，更近何器？',
    options: [
      { text: '朴石', gloss: '以朴为器', primary: { traitId: 12, delta: -0.8 } },
      { text: '木铎', gloss: '以朴为用', primary: { traitId: 12, delta: -0.4 } },
      { text: '钟', gloss: '以重为器', primary: { traitId: 12, delta: 0.0 } },
      { text: '磬', gloss: '以雅为器', primary: { traitId: 12, delta: 0.4 } },
      { text: '琴', gloss: '以文为器', primary: { traitId: 12, delta: 0.8 } },
      { text: '黄钟大吕', gloss: '以极为器', primary: { traitId: 12, delta: 1.2 } },
    ],
  },
  {
    id: 'wp-048',
    format: 'situational',
    prompt: '言辞之度',
    promptGloss: '著书立说，汝如何权衡言辞之轻重？',
    options: [
      { text: '寡言', gloss: '以寡为慎', primary: { traitId: 12, delta: -1.2 } },
      { text: '言简意赅', gloss: '以简为慎', primary: { traitId: 12, delta: -0.6 } },
      { text: '言之有物', gloss: '以实为慎', primary: { traitId: 12, delta: -0.2 } },
      { text: '言之成理', gloss: '以理为慎', primary: { traitId: 12, delta: 0.2 } },
      { text: '言之动听', gloss: '以巧为慎', primary: { traitId: 12, delta: 0.6 } },
      { text: '惊世骇俗', gloss: '以极为慎', primary: { traitId: 12, delta: 1.2 } },
    ],
  },
  {
    id: 'wp-049',
    format: 'situational',
    prompt: '黄昏对话于广场',
    promptGloss: '黄昏时分在广场上与众人辩论，有人质疑你的观点一无是处，你如何回应？',
    options: [
      { text: '循循善诱', gloss: '以问为答，引导思考', primary: { traitId: 12, delta: 0.8 }, secondary: [{ traitId: 4, delta: 0.2 }] },
      { text: '据理力争', gloss: '以逻辑明辨是非', primary: { traitId: 1, delta: 0.4 } },
      { text: '一笑置之', gloss: '不与之争，超然物外', primary: { traitId: 9, delta: -0.6 } },
      { text: '勃然而怒', gloss: '拍案而起，怒斥其妄', primary: { traitId: 5, delta: 1.2 } },
      { text: '沉默不语', gloss: '以沉默为辩', primary: { traitId: 6, delta: 0.6 } },
      { text: '自省反思', gloss: '反思己论是否有误', primary: { traitId: 11, delta: -0.4 } },
    ],
  },
  {
    id: 'wp-050',
    format: 'imagery',
    prompt: '烛下阅旧稿',
    promptGloss: '烛光下翻阅自己早年写下的文字，看着那些曾经深信不疑的观点，你作何想？',
    options: [
      { text: '少年意气', gloss: '当年之我何其勇也', primary: { traitId: 4, delta: 0.8 } },
      { text: '今是昨非', gloss: '今日之我嘲昨日之我', primary: { traitId: 10, delta: 0.6 } },
      { text: '一以贯之', gloss: '初心未改，始终如一', primary: { traitId: 7, delta: 1.0 } },
      { text: '恍如隔世', gloss: '此心已非彼心', primary: { traitId: 9, delta: -0.4 } },
      { text: '付之一炬', gloss: '烧掉旧稿，从头开始', primary: { traitId: 11, delta: 1.2 } },
      { text: '誊录成册', gloss: '整理保存以为镜鉴', primary: { traitId: 8, delta: 0.0 } },
    ],
  },
  {
    id: 'wp-r13',
    format: 'ranking',
    prompt: '求真四道',
    promptGloss: '「逻辑、经验、直觉、启示」── 求真之道，何者最可信？',
    options: [
      { text: '逻辑为上', gloss: '以推理为基', primary: { traitId: 8, delta: 0.6 } },
      { text: '经验为基', gloss: '以经验为本', primary: { traitId: 8, delta: -0.4 } },
      { text: '直觉为重', gloss: '以悟性为归', primary: { traitId: 8, delta: 0.8 } },
      { text: '启示为归', gloss: '以上示为信', primary: { traitId: 8, delta: -0.8 } },
      { text: '四者皆用', gloss: '兼收并蓄', primary: { traitId: 8, delta: 0.0 } },
      { text: '择善而从', gloss: '因事而择', primary: { traitId: 8, delta: 0.4 } },
    ],
  },
  {
    id: 'wp-a14',
    format: 'aesthetic',
    prompt: '斜阳古堡与晨曦海岸',
    promptGloss: '斜阳古堡之沧桑与晨曦海岸之新生，两种哲思之境，何者更契汝心？',
    options: [
      { text: '前者', gloss: '前者更合心意', primary: { traitId: 2, delta: 1.2 } },
      { text: '偏前者', gloss: '略偏前者之境', primary: { traitId: 2, delta: 0.6 }, secondary: [{ traitId: 6, delta: 0.2 }] },
      { text: '兼爱之', gloss: '两种意境皆有可取', primary: { traitId: 2, delta: 0.0 }, secondary: [{ traitId: 6, delta: 0.3 }] },
      { text: '偏后者', gloss: '略偏后者之境', primary: { traitId: 2, delta: -0.6 }, secondary: [{ traitId: 6, delta: -0.2 }] },
      { text: '后者', gloss: '后者更入君心', primary: { traitId: 2, delta: -1.2 } },
      { text: '皆不取', gloss: '超乎二者之外', primary: { traitId: 2, delta: -1.4 }, secondary: [{ traitId: 1, delta: 0.2 }] },
    ],
  },
  {
    id: 'wp-053',
    format: 'situational',
    prompt: '学生质疑师道',
    promptGloss: '你的学生对你说"老师，你的哲学已经过时了"，你如何应对？',
    options: [
      { text: '虚心请教', gloss: '请学生说明为何过时', primary: { traitId: 4, delta: 0.6 } },
      { text: '捍卫尊严', gloss: '以更精深之理驳斥之', primary: { traitId: 7, delta: 1.0 } },
      { text: '欣然接纳', gloss: '闻过则喜，与学生共论', primary: { traitId: 11, delta: 0.4 } },
      { text: '不屑一顾', gloss: '孺子之见，何足挂齿', primary: { traitId: 3, delta: -1.0 } },
      { text: '以问代答', gloss: '反问其何为不过时', primary: { traitId: 12, delta: 0.8 } },
      { text: '赠书自明', gloss: '赠以旧著，令其自读', primary: { traitId: 8, delta: -0.4 } },
    ],
  },
  {
    id: 'wp-054',
    format: 'imagery',
    prompt: '荒原独行',
    promptGloss: '独自穿过一片荒原，天地之间唯你一人，你心中所感为何？',
    options: [
      { text: '自由无羁', gloss: '人的灵魂在此刻解放', primary: { traitId: 7, delta: 1.2 }, secondary: [{ traitId: 3, delta: 0.3 }] },
      { text: '荒诞虚无', gloss: '世界本无意义', primary: { traitId: 11, delta: 1.4 } },
      { text: '敬畏自然', gloss: '天地不仁以万物为刍狗', primary: { traitId: 6, delta: 0.2 } },
      { text: '孤独之痛', gloss: '他人即地狱', primary: { traitId: 5, delta: -0.6 } },
      { text: '寻求归途', gloss: '此身何处是归程', primary: { traitId: 2, delta: 0.8 } },
      { text: '坚定前行', gloss: '走自己的路', primary: { traitId: 3, delta: 0.4 } },
    ],
  },
  {
    id: 'wp-r14',
    format: 'ranking',
    prompt: '立言之要',
    promptGloss: '「真、新、深、美」── 立言之要，何者最重？',
    options: [
      { text: '真为先', gloss: '以真实为本', primary: { traitId: 7, delta: 0.4 } },
      { text: '新为上', gloss: '以创新为上', primary: { traitId: 4, delta: 0.8 } },
      { text: '深为归', gloss: '以深刻为归', primary: { traitId: 7, delta: 1.2 } },
      { text: '美为度', gloss: '以审美为度', primary: { traitId: 7, delta: -0.4 } },
      { text: '四者相济', gloss: '兼而用之', primary: { traitId: 7, delta: 0.0 } },
      { text: '以说为要', gloss: '以说服为归', primary: { traitId: 7, delta: 0.6 } },
    ],
  },
  {
    id: 'wp-a13',
    format: 'aesthetic',
    prompt: '月色朦胧与烈阳高照',
    promptGloss: '月色朦胧之迷离与烈阳高照之明澈，两种认知之境，何者更见真实？',
    options: [
      { text: '前者', gloss: '前者更合心意', primary: { traitId: 10, delta: 1.2 } },
      { text: '偏前者', gloss: '略偏前者之境', primary: { traitId: 10, delta: 0.6 }, secondary: [{ traitId: 6, delta: 0.2 }] },
      { text: '兼爱之', gloss: '两种意境皆有可取', primary: { traitId: 10, delta: 0.0 }, secondary: [{ traitId: 6, delta: 0.3 }] },
      { text: '偏后者', gloss: '略偏后者之境', primary: { traitId: 10, delta: -0.6 }, secondary: [{ traitId: 6, delta: -0.2 }] },
      { text: '后者', gloss: '后者更入君心', primary: { traitId: 10, delta: -1.2 } },
      { text: '皆不取', gloss: '超乎二者之外', primary: { traitId: 10, delta: -1.4 }, secondary: [{ traitId: 1, delta: 0.2 }] },
    ],
  },
  {
    id: 'wp-r15',
    format: 'ranking',
    prompt: '评价四维',
    promptGloss: '「对错、好坏、美丑、有用无用」── 评价事物，何者最重？',
    options: [
      { text: '是非对错', gloss: '以真伪为度', primary: { traitId: 5, delta: 0.8 } },
      { text: '善恶好坏', gloss: '以道德为度', primary: { traitId: 5, delta: 0.4 } },
      { text: '美丑雅俗', gloss: '以审美为度', primary: { traitId: 5, delta: -0.4 } },
      { text: '有用无用', gloss: '以实用为度', primary: { traitId: 5, delta: -0.8 } },
      { text: '因事而异', gloss: '视情境而定', primary: { traitId: 5, delta: 0.0 } },
      { text: '皆不执着', gloss: '超越二元对立', primary: { traitId: 5, delta: 1.2 } },
    ],
  },
  {
    id: 'wp-a14',
    format: 'aesthetic',
    prompt: '象牙塔顶与熙攘街头',
    promptGloss: '象牙塔顶之思辩与熙攘街头之烟火，哲学家身处，何者更动汝心？',
    options: [
      { text: '前者', gloss: '前者更合心意', primary: { traitId: 10, delta: 1.2 } },
      { text: '偏前者', gloss: '略偏前者之境', primary: { traitId: 10, delta: 0.6 }, secondary: [{ traitId: 6, delta: 0.2 }] },
      { text: '兼爱之', gloss: '两种意境皆有可取', primary: { traitId: 10, delta: 0.0 }, secondary: [{ traitId: 6, delta: 0.3 }] },
      { text: '偏后者', gloss: '略偏后者之境', primary: { traitId: 10, delta: -0.6 }, secondary: [{ traitId: 6, delta: -0.2 }] },
      { text: '后者', gloss: '后者更入君心', primary: { traitId: 10, delta: -1.2 } },
      { text: '皆不取', gloss: '超乎二者之外', primary: { traitId: 10, delta: -1.4 }, secondary: [{ traitId: 1, delta: 0.2 }] },
    ],
  },
];
